# Conférenciers invités {-}

```{block, type='protip'}

#### Rejoignez-nous à l’émission de radio matinale #OTESSA23 lundi, mardi, mercredi 29 30 31 mai de 7h30 à 8h30 (heure de l’Est) à [https://voiced.ca](https://voiced.ca){target="_blank"}
```

## Samedi 27 mai {-}

### Anne-Marie Scott {-}

*non affilié* 

**5 choses que vous devez savoir avant d’acheter Edtech**


S’appuyant sur des expériences de plus de 20 ans dans la technologie de l’enseignement supérieur, travaillant dans des contextes de technologie commerciale et ouverte, cette conférence propose que l’approvisionnement en technologies éducatives est fondamentalement défectueux à la fois en tant que pratique et en tant que processus. Les processus institutionnels tels que les achats ont tendance à être absents des conversations sur l’éducation numérique, souvent reconnues comme problématiques mais aussi en dehors de notre sphère d’influence ou de notre domaine d’expertise. Partant du principe que la pédagogie et la technologie sont enchevêtrées de manière complexe, c’est en fait le contraire qui devrait être vrai. Les technologies éducatives que nous utilisons ne sont pas des outils et doivent être traitées comme des questions de qualité lorsque nous considérons à quoi pourrait ressembler une bonne éducation numérique et quel est, selon nous, le but de l’éducation.

La prise en compte de l’éthique est souvent absente de l’achat de technologie, largement basée sur des hypothèses instrumentalistes sur la neutralité des technologies. Les « meilleures pratiques » en matière d’approvisionnement du secteur public nous obligent également à utiliser de mauvais substituts pour nos valeurs, objectifs et contextes éducatifs, et créent de nouveaux risques et responsabilités pour les institutions, tout en cherchant à minimiser les autres. Alors que cette conférence explorera les solutions potentielles au processus et aux pratiques d’approvisionnement actuels, la question qui reste en suspens est de savoir si nous achetons et/ou utilisons simplement trop de technologie éducative, et si, afin de parvenir à des formes d’éducation plus durables et justes sur le plan environnemental, devrions-nous adopter une approche de décroissance de la technologie éducative plus généralement ?

Quelle quantité d’approvisionnement en edtech, aussi bien exécutée soit-elle, est trop ?

**Bio**

TBA

### Nicole Johnson {-}

*Canadian Digital Learning Research Association/Association canadienne de recherche sur la formation en ligne*

**Tendances de l’apprentissage numérique dans l’enseignement postsecondaire au Canada**

Joignez-vous à la Dre Nicole Johnson, directrice générale de la Canadian Digital Learning Research Association/Association canadienne de recherche sur la formation en ligne (CDLRA/ACRFL), alors qu’elle partage l’évolution des tendances de l’apprentissage numérique au fil du temps et discute de ce que cela signifie pour l’avenir de l’enseignement postsecondaire au Canada. Depuis 2017, la CDLRA/ACRFL mène des sondages pancanadiens annuels pour suivre les tendances liées à l’apprentissage numérique dans les établissements postsecondaires canadiens. En particulier, depuis 2020, la CDLRA/ACRFL enquête sur l’impact continu de la pandémie sur la prestation des cours et les pratiques d’enseignement. Grâce à sa pratique indépendante de recherche et de conseil, le Dr Johnson a également travaillé sur plusieurs autres études liées aux expériences des professeurs avec la technologie, catégorisant les expériences d’apprentissage par modalité et l’avenir de l’enseignement supérieur. Dans cette présentation, le Dr Johnson discutera des défis auxquels sont confrontés les établissements (et du secteur postsecondaire dans son ensemble), de ce que l’avenir pourrait réserver et des recommandations pour le secteur.

**Bio**

Dr. Nicole Johnson est directrice générale de l'Association canadienne de recherche sur l'apprentissage numérique (ACDLR), où elle dirige des études de recherche longitudinales annuelles explorant les tendances pancanadiennes liées à l'apprentissage numérique dans les établissements postsecondaires. Elle possède également une pratique indépendante de recherche et de consultation et travaille au sein d'équipes de recherche à l'Université Royal Roads (Victoria, C.-B.) et à Bay View Analytics (Oakland, CA). Le Dr Johnson travaille dans le domaine de l'éducation depuis plus de deux décennies, se concentrant sur l'apprentissage numérique depuis près de 15 ans. Ses principaux intérêts de recherche comprennent le suivi des tendances au niveau macro de l'apprentissage numérique au niveau postsecondaire, la définition et l'opérationnalisation des termes clés associés à l'apprentissage numérique, l'étude des expériences des professeurs avec la technologie, l'exploration de l'avenir de l'enseignement supérieur et une meilleure compréhension de la façon dont les adultes apprennent de manière informelle. dans des contextes numériques.

### Alec Couros {-}

*University of Regina*

**Exploiter la puissance de l’IA dans l’éducation : opportunités et défis**

Dans cette présentation, le Dr Alec Couros explorera les possibilités et l’impact passionnants de l’IA dans l’éducation, en se concentrant sur des outils tels que ChatGPT. Avec la capacité de fournir des expériences d’apprentissage personnalisées, l’IA a le potentiel de transformer la façon dont nous enseignons et apprenons. Cependant, son intégration dans la salle de classe soulève également d’importantes préoccupations éthiques et sociétales. Le Dr Couros examinera à la fois les opportunités et les défis de l’IA dans l’éducation. Les participants repartiront avec une meilleure compréhension du potentiel de l’IA à avoir un impact positif sur l’apprentissage et la réussite des élèves, ainsi que les considérations et les défis qui doivent être abordés afin de l’adopter pleinement dans nos environnements d’apprentissage.

Bio
TBA

### Brad Wuetherick {-}

*University of British Columbia – Okanagan Campus*

**Composer les tensions entre les savoirs autochtones et l’éducation ouverte : Explorer les 6R de Lar-Son pour les REL autochtones dans la pratique**

De nombreuses conversations autour de l’éducation ouverte se concentrent sur un cadre eurocentrique du droit d’auteur et des droits de propriété intellectuelle qui sont parfois en tension avec les systèmes de connaissances autochtones. Alors que les communautés et les universitaires autochtones souhaitent que l’accès aux savoirs autochtones fasse davantage partie intégrante d’un paysage postsecondaire décolonisé et indigénisé, cette séance explorera les sujets de préoccupation concernant les intersections entre les ressources éducatives libres (REL) et les savoirs autochtones. En utilisant le cadre des 6R des REL autochtones de Lar-Son (2022) pour faire progresser les connaissances autochtones grâce à des pédagogies et des ressources d’éducation ouverte, cette session explorera certains des principes et pratiques pour s’engager avec les communautés autochtones dans la création de REL. De plus, la session discutera de quatre études de cas différentes sur les REL mettant en vedette la perspective autochtone et les connaissances autochtones de partout au Canada, y compris d’un volume édité « en préparation », qui centre les modes de connaissance, la culture, les expériences et les visions du monde autochtones dans le travail de pédagogie de l’éducation et développement des REL.

**Bio**

Brad Wuetherick est vice-recteur aux programmes universitaires, à l'enseignement et à l'apprentissage au campus Okanagan de l'UBC. D'ascendance métisse et européenne, Brad est un spécialiste de l'enseignement et de l'apprentissage dans l'enseignement supérieur, avec un intérêt croissant pour le mentorat autochtone, les parcours des étudiants autochtones vers la recherche et l'équité dans l'enseignement et l'apprentissage. Au cours de la dernière décennie, il a également participé à plusieurs projets liés aux technologies éducatives dans l'enseignement supérieur, y compris l'utilisation des eportfolios. Brad a auparavant occupé divers postes de direction dans l'enseignement et l'apprentissage à l'Université Dalhousie, à l'Université de la Saskatchewan et à l'Université de l'Alberta.

## Lundi 29 mai {-}

### Jennifer Wemigwans {-}

*OISE University of Toronto*

**Offres groupées numériques : un calcul et une réinvention**

Les ensembles numériques créent un espace culturel pour le savoir autochtone grâce à l’utilisation de nouveaux les technologies. Le concept des offres groupées numériques est issu d’une tradition qui respecte la diversité Les aînés et les gardiens du savoir en tant que gardiens des ensembles de connaissances communautaires. Partage Les ensembles numériques en ligne représentent de nouveaux espaces pour le savoir autochtone sous la forme de Éducation. Les forfaits numériques sont à la fois un calcul et une réinvention de l’espace en ligne. Pour les non-publics autochtones, les forfaits numériques les mettent au défi de sortir de leurs systèmes codifiés et apprendre une nouvelle façon d’être et de percevoir le monde. Pour les publics autochtones, numérique Les ensembles sont une nouvelle façon de partager l’éclat de diverses connaissances autochtones avec de nouveaux générations.

**Bio**

Jennifer Wemigwans, PhD, est originaire du territoire non cédé de Wiikwemkoong sur l'île Manitoulin, en Ontario. Elle est productrice de nouveaux médias, écrivaine et chercheuse spécialisée dans la convergence entre l'éducation, le savoir autochtone et les technologies des nouveaux médias. Son livre A Digital Bundle: Protecting and Promoting Indigenous Knowledge Online (2018) explore les perspectives de l'éducation au savoir autochtone et des projets numériques dans un monde en réseau. Le Dr Wemigwans est fier de travailler à inverser l'utilisation conventionnelle des médias en révélant le potentiel de l'expression culturelle autochtone et du savoir autochtone grâce aux nouvelles technologies, à l'éducation et aux arts. Elle est professeure adjointe au programme d'éducation des adultes et de développement communautaire à l'OISE de l'Université de Toronto.

### Isabel Pedersen{-}

*Ontario Tech University*

**Choc et crainte : composition de l’IA générative, adaptation culturelle et éducation postsecondaire**

Le lancement de ChatGPT d’OpenAI a été un événement dramatique faisant de l’intelligence artificielle générative un phénomène courant. La journaliste de données, Katharina Buchholz, explique que « ChatGPT a gagné un million d’utilisateurs cinq jours seulement après son lancement en novembre » de 2022 (Statista, 2023). L’IA générative peut produire des phrases, des paragraphes et des documents stylistiquement corrects dans une multitude de genres. Il peut produire des images visuelles et des vidéos de qualité professionnelle. Bien que fortement débattu, on pourrait soutenir que l’IA générative « crée ». Par conséquent, l’IA générative peut aider les élèves à créer de l’art, à écrire ou à collaborer avec d’autres élèves. Cependant, l’IA générative peut accomplir toutes ces tâches pour les étudiants sans nécessiter beaucoup d’effort humain, ce qui perturbe le principe général d’apprentissage de la composition. Dans le même temps, ses créations sont susceptibles de produire de fausses informations et des résultats discriminatoires en raison des sources de formation. Cette présentation fait valoir que le choc provoqué par les grandes entreprises technologiques, lançant ces produits à travers la rhétorique du battage médiatique et de la peur, alimente l’adoption massive plutôt qu’une approche mesurée. Les éducateurs, les étudiants et les administrateurs universitaires sont confrontés à la gestion de l’adaptation culturelle aux générateurs d’IA qui remettent en question les traditions de créativité humaine et d’éducation formelle. S’appuyant sur les études et la rhétorique des médias (Pedersen et Iliadis 2020), les études sur la littératie numérique (Duin et Pedersen 2021) et les études critiques sur l’IA (Bender, Gebru, McMillan-Major et Shmitchell 2021), cette discussion pointe vers le processus de re- imaginer les attentes d’apprentissage dans les cours universitaires au milieu de l’assaut de l’émergence de l’IA générative.

**Bio**

TBA

## Mardi 30 mai {-}

### Bonnie Stewart {-} 

*University of Windsor*

**L’éducation numérique à l’ère des données : que faisons-nous maintenant ?**



Session Abstract: TBA

**Bio**

TBA

### Leo Havemann and Panel Members {-}

*Open University / UCL*

**Recherche à la limite de l’ouverture : Réflexions des membres de GO-GN**


GO-GN, le Global OER Graduate Network, rassemble un noyau de doctorants actuels travaillant sur des sujets d’éducation ouverte, ainsi que l’équipe GO-GN de l’Open University, des anciens, d’autres chercheurs et d’autres voyageurs à travers l’espace ouvert. Et même si nous voyageons sans uniformes ni transporteurs, comme les membres des GO-GNers de Starfleet, nous allons audacieusement, essayant de repousser les limites de la connaissance sur le terrain. Reconnaissant les multiples sens dans lesquels l’éducation peut être ouverte, nous abordons le concept d’ouverture sous différents angles et utilisons une gamme de méthodes.

Dans cette table ronde, les membres du réseau réfléchiront sur le quoi, le pourquoi et le comment de leurs parcours doctoraux, et inviteront les participants à la session dans notre conversation.

**Bio**

TBA

## Vendredi 2 juin {-}

### Nadia Naffi {-}

*Université Laval*

**Adopter le métaverse : FormationMeta et l'avenir de l'expérience d'apprentissage immersif (en français)**


Plongez dans le monde passionnant de FormationMeta, un projet exploratoire novateur de 14 semaines mené par la Chaire de leadership pédagogique sur les pratiques pédagogiques innovantes en contexte numérique de l’Université Laval, en partenariat avec la Bibliothèque de l’Université Laval et l’OVA. Ce projet novateur a offert aux concepteurs et aux enseignants d’expériences d’apprentissage de l’Université Laval une expérience authentique pour cultiver leurs compétences dans la conception et le développement d’expériences d’apprentissage immersives dans la réalité virtuelle et le métavers. Impliquant des étudiants de diverses disciplines telles que la technologie éducative, l’art et la conception de jeux, le projet a exploité la puissance du logiciel StellarX.ai pour créer une formation immersive sur mesure adaptée à la clientèle de la bibliothèque.

Présentée en français, cette conférence dévoilera des recommandations émergentes pour éclairer les équipes éducatives désireuses d’adopter des expériences d’apprentissage immersives. Le conférencier abordera des questions urgentes, notamment les possibilités actuelles et les avancées technologiques futures, telles que l’IA générative, les compétences essentielles pour développer des expériences d’apprentissage dans le métaverse et les stratégies de formation de groupes d’experts en éducation et en technologie éducative pour créer des expériences immersives qui répondent efficacement aux groupes d’apprenants tout en respectant des principes éthiques, équitables et inclusifs.

**Bio**

TBA

### Randy LaBonte {-}

*Vancouver Island University & Canadian eLearning Network*

**Principes de conception pour l’apprentissage numérique et les normes NSQOL : points communs et différences**

Rejoignez cette session pour acquérir une compréhension des principes de conception et d’organisation afin d’aider à informer la qualité des pratiques des enseignants et des leaders de l’apprentissage en ligne de la maternelle à la 12e année. Découvrez les principes de conception d’apprentissage en ligne basés au Canada et leurs points communs et leurs différences avec les normes nationales américaines pour un apprentissage en ligne de qualité (NSQOL), leur application à la pédagogie et à la pratique, et comment l’élucidation et la clarification des principes de conception et d’organisation aident à informer le leadership et politique administrative pour un apprentissage en ligne de qualité.

**Bio**

TBA