# Mardi 30 Mai 2023 | En Personne À L’Université York

```{block, type='protip'}

#### Rejoignez-nous à l’émission de radio matinale #OTESSA23 lundi, mardi, mercredi 29 30 31 mai de 6h30 à 7h30 (heure de l’Est) à [https://voiced.ca](https://voiced.ca){target="_blank"}
```

### Session Types {-}

```{block, type='protip'}


#### ✨ Note{-}

***All times are in Eastern Time (Canada)***
```

```{block, type='keynote'}

#### Keynote

```

```{block, type='speaker'}

#### Invited Speaker

```

```{block, type='session'}

#### Regular Session

```

```{block, type='social'}

#### Social Session

```

```{block, type='vendor'}


#### Vendor

```

```{block, type='workshop'}


#### Workshop

```

---

## Petit-déjeuner continental fourni | 8:00-9:00 {-}

## Bureau d’accueil ouvert | 8:00 - 11:30 {-}

## Bienvenue à la conférence, annonces et reconnaissance des terres | 9:00-9:15 {-}

<mark>**Life Sciences Building LSB 103 @ York**</mark>

<mark>[**Lien de session**](https://uvic.zoom.us/j/89902859924?pwd=VisxNW1GUW5KWnJldW1DRjF2d0Rmdz09){target="_blank"}</mark>

## Casser | 9:15-9:30 {-}

## Séance simultanée 9 | 9:30-10:30 {-}

1 hour

### Séance simultanée 9.1 |  Formations d’apprentissage et d’enseignement en ligne {-}

<mark>**Life Sciences Building LSB 105**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa)**</mark>

```{block, type='session'}

#### 9:30-10:00 | **Développer des compétences en éducation ouverte dans les programmes de formation des enseignants** |  Recherche {-}

***Michael Paskevicius*** | *University of Victoria*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Les chercheurs ont fait valoir que les enseignants de la maternelle à la 12e année sont bien placés pour adopter et développer des aspects de l’éducation ouverte. DeBarger (2019), suggère que les ressources éducatives ouvertes (REL), en particulier, peuvent être une alternative efficace aux ressources traditionnelles pour améliorer à la fois l’agence des étudiants et des enseignants. Marcus-Quinn et Hourigan (2017), reconnaissent les REL dans le développement et l’amélioration de l’efficacité de l’enseignement grâce à un partage plus ouvert et au développement de la pédagogie. De même, Allen et Katz (2019) postulent que les enseignants sont bien placés pour faire évoluer les pratiques éducatives ouvertes et ont constaté que l’augmentation de leurs opportunités de s’engager ouvertement dans un environnement sûr peut avoir un impact sur leur auto-efficacité et leur volonté de partager ouvertement à l’avenir (Allen & Katz, 2022). Pourtant, les chercheurs ont fait valoir que la recherche et la pratique de l’éducation ouverte de la maternelle à la 12e année sont sous-développées, manquent d’orientation politique et que, par conséquent, la sensibilisation reste faible (Blomgren, 2018 ; Blomgren et MacPherson, 2018).

Les programmes de formation des enseignants ont un rôle clé à jouer dans le développement des littératies d’éducation ouverte pendant la formation des enseignants. En adoptant une vision élargie de l’éducation ouverte, cela peut inclure le développement de compétences autour des approches pédagogiques, de la sélection des ressources, de la conception des évaluations et de l’utilisation de la technologie qui est motivée par l’ouverture. Il semble y avoir des thèmes similaires dans les programmes de formation des enseignants tels que l’accessibilité, l’engagement communautaire, l’apprentissage axé sur la recherche, la multimodalité, l’état d’esprit de croissance, la collaboration, la pleine conscience et le multiculturalisme qui s’alignent bien sur les pratiques éducatives ouvertes.

Cette présentation se concentrera sur les façons dont les formateurs d’enseignants pourraient intégrer l’aspect de l’éducation ouverte dans les programmes de formation des enseignants. Je partagerai les résultats d’une revue de la littérature sur l’éducation ouverte dans les contextes de la maternelle à la 12e année, une enquête préliminaire qui identifie les lacunes de sensibilisation liées à l’éducation ouverte, et inviterai des réflexions sur la manière dont les formateurs d’enseignants pourraient introduire l’éducation ouverte aux enseignants émergents de manière significative.

</p>
</details>
```



### Séance simultanée 9.2 |  Formations d’apprentissage et d’enseignement en ligne {-}

<mark>**Life Sciences Building LSB 101**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa_2)**</mark>

```{block, type='session'}

#### 9:30-10:00 | **Appartenance, parenté, connectivité ou présence sociale ? Chevauchements et différences dans l’apprentissage en ligne** |  Recherche {-}

***Behnoosh Khoramrooz, Mariel Miller & Valerie Irvine*** | *University of Victoria*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Se sentir connecté et soutenu dans les études liées à l’apprentissage en ligne a été mentionné comme un facteur essentiel de motivation, d’engagement et de persévérance. Suivre des éléments clés comme avoir une conversation individualisée, fournir un soutien, promouvoir la coopération, faire preuve de sensibilisation, montrer de l’attention, de l’acceptation et de l’aide et offrir la possibilité d’avoir une communication amicale nous amène à différentes constructions dans la région, comme la relation, le sentiment d’appartenance, la connectivité , et présence sociale. La question est, quelles sont les différences entre ces constructions ? Et comment chacun d’eux contribue au contexte d’apprentissage en ligne. Cette session se consacre à la comparaison de ces concepts en se référant à leurs définitions, leurs racines, leurs théories et leurs contributions à la recherche sur l’apprentissage en ligne.

</p>
</details>
```

```{block, type='session'}

#### 10:00-10:30 | **Apprentissage hybride en Ontario pendant les fermetures d’urgence liées à la COVID-19** |  Recherche {-}

***Beyhan Farhadi*** | *York University*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Cette présentation aborde l’apprentissage en ligne pendant les fermetures d’urgence du COVID-19 à travers le prisme de l’analyse critique des politiques, à travers laquelle la politique est comprise non seulement comme une réponse aux problèmes, mais aussi comme une source de problèmes. À partir de la deuxième phase d’une étude de deux ans sur l’adoption de la politique d’éducation COVID-19 par les enseignants du secondaire, nous analysons le contexte et l’expansion de l’apprentissage hybride en Ontario. L’apprentissage hybride fait généralement référence à l’enseignement simultané d’étudiants en ligne par un enseignant avec des étudiants en personne. En mars et avril 2022, nous nous sommes entretenus avec neuf enseignants de trois districts scolaires pour comprendre les variables ayant un impact sur leur mise en œuvre de l’apprentissage hybride dans un contexte de crise en évolution rapide qui, selon notre étude, a eu un impact sur le bien-être des élèves et des enseignants, la charge de travail et l’équité en matière d’éducation. Les résultats juxtaposent les objectifs déclarés de l’éducation publique et les exigences de la crise aux réalités auxquelles sont confrontés les étudiants et les enseignants. Cela reflète les préoccupations d’équité, y compris l’accès à Internet et à la technologie, la littératie numérique et les considérations de confidentialité et de surveillance.

</p>
</details>
```

### Séance simultanée 9.3 |  Maintenir un changement positif {-}

<mark>**Life Sciences Building LSB 103**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa_3)**</mark>

```{block, type='session'}

#### 9:30-10:00 | **Écrire attentivement sur la sécurité culturelle autochtone et l’humilité culturelle : une réflexion de colons engagés dans la réconciliation dans le développement des REL** |  Pratique {-}

***Deb Nielsen & Emily Ballantyne*** | *College of New Caledonia*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Quelles sont les façons éthiques de s’engager dans la réconciliation en tant que colons qui souhaitent intégrer les contextes autochtones et la sécurité culturelle dans une ressource éducative ouverte ? Dans cette présentation, nous discutons des stratégies, des succès et des défis liés à l’engagement dans le développement collaboratif de ressources d’éducation ouverte dans un projet où les principaux collaborateurs étaient des colons qui voulaient s’engager profondément dans la réconciliation. Cette présentation décrit notre parcours et les façons dont nous nous sommes engagés auprès de diverses parties prenantes pour produire notre ressource de manière éthique, réfléchie et soignée.

Un aspect principal de notre discussion portera sur la façon dont nous nous sommes engagés dans la collaboration, la discussion communautaire et la recherche d’une autorité extérieure auprès d’experts autochtones. Nous discutons de nos propres expériences avec l’humilité culturelle et les autres façons de savoir. Nous ne parlons pas en tant qu’experts ayant des racines et des relations profondes dans les communautés avec lesquelles nous nous sommes engagés ; au lieu de cela, nous parlons en tant que nouveaux arrivants et colons engagés dans ce travail et luttant pour savoir comment le faire mieux. En effet, cette discussion portera sur certaines des stratégies que nous avons essayées et sur les leçons que nous avons apprises et que nous souhaitons appliquer aux projets futurs.

</p>
</details>
```

```{block, type='session'}

#### 10:00-10:30 | **L’écriture d’intelligence artificielle dans l’enseignement supérieur : une perspective de centre d’enseignement et d’apprentissage** |  Pratique {-}

***Emily Ballantyne*** | *Mount Saint Vincent University*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Le lancement de ChatGPT a provoqué un changement sismique dans le domaine de l’enseignement supérieur. Au milieu des appels à l’interdire dans les écoles et à dénoncer la fin de disciplines entières (Thomas 
2023 ; Herman 2022 ; Vincent 2023, Stokel-Walker 2022), il y a également eu de grands élans d’enthousiasme et d’optimisme alors que les professeurs et les étudiants se demandent comment cela façonner leur expérience éducative à l’avenir. La crise actuelle provoquée par les générateurs de texte à intelligence artificielle est avant tout pédagogique : en quoi cet outil change-t-il notre approche de l’apprentissage ?

Cette présentation explorera la question émergente de l’écriture artificiellement intelligente du point de vue d’un centre d’enseignement et d’apprentissage. Avec pour mission de soutenir les professeurs de plusieurs disciplines engagés dans l’évaluation et la rétroaction, c’est notre travail (et notre plaisir !) D’aider à trouver des solutions aux problèmes d’enseignement courants. Dans le cas de ChatGPT, cependant, des stratégies ciblées fondées sur des preuves doivent encore être développées. Dans le même temps, les conversations sur l’outil sont très chargées et alimentées par une couverture médiatique intensive de qualité variable, toutes produites extrêmement rapidement et souvent écrites pour être très incendiaires et alarmistes. Dans notre contexte, cela signifie qu’en plus de fournir des informations précises et utiles, nous devons également travailler pour décoder et déterminer la désinformation. Il est de notre rôle d’aider à appliquer les connaissances existantes en matière d’enseignement et d’apprentissage à ce problème nouveau et nouveau. C’est aussi notre rôle d’écouter et de diffuser l’expérience vécue des professeurs et des étudiants engagés dans ce travail. De plus, il est de notre rôle d’être co-créateurs de ces nouvelles connaissances alors que nous travaillons aux côtés de nos pairs du corps professoral pour aider, par essais et erreurs, à naviguer dans ce nouveau paysage éducatif dans lequel nous nous trouvons

</p>
</details>
```

## Casser | 10:30-11:00 {-}

## Non-conférence sur l’éducation numérique, en ligne et ouverte (sur place à York) | 11:00-12:00 {-}

**Emplacements répartis sur LSB 101, 103, 105, 107. Voir le site Web du programme OTESSA pour plus de détails.**

Une non-conférence est une session axée sur les participants destinée à réduire l’accent mis sur les discours formels et à éviter les aspects hiérarchiques d’une session de conférence didactique. Tous les participants au Congrès sont invités à participer à cette non-conférence en face à face ; cependant, les participants inscrits à la conférence OTESSA recevront une invitation à suggérer des sujets et à voter pour sélectionner à l’avance les sujets de la salle de sous-commission. Au moment de cette session, les affectations de sujet à salle seront terminées et publiées sur le site Web de notre programme à <https://otessa.org/2023/program/>. Vous êtes invités à vous déplacer entre les salles thématiques et à aller et venir à votre guise ! Nous nous réjouissons d’accueillir des discussions ciblées sur vos sujets favoris ! Veuillez noter qu’il s’agit de la non-conférence en personne. Il y aura également une contre-conférence en ligne qui aura lieu le vendredi 2 juin de 12h30 à 13h15 dans une salle Zoom dans le cadre de la conférence OTESSA.Séance hors conférence TBA


## Casser | 12:00-1:30 {-}

## Séance parallèle 10 | Conférencier invité  | 1:30-2:15 {-}

45 Minutes

### Séance parallèle 10.1 {-}

<mark>**Life Sciences Building LSB 103**</mark>

<mark>[**Lien de session**](https://uvic.zoom.us/j/86250728368?pwd=dEFWYXJQcy9uVm91dDArT0RzanVNQT09){target="_blank"}</mark>

```{block, type='speaker'}

#### Bonnie Stewart | University of Windsor {-} 

*L’éducation numérique à l’ère des données : que faisons-nous maintenant ?*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Que signifie l’écosystème numérique actuel de surveillance numérique omniprésente, d’exploration de données et d’intelligence artificielle envahissante pour les possibilités participatives de la pédagogie ouverte et de l’apprentissage numérique ? Qu’est-ce qui constitue une réponse critique et éthique à cet écosystème de plus en plus colonisateur et extractif ?

S’appuyant sur deux modèles de changement fondamentaux – et potentiellement contradictoires – qui se croisent actuellement dans l’apprentissage numérique, cette conférence se concentrera sur le dilemme éthique que cette intersection crée pour l’éducation ouverte et numérique. D’un côté se trouvent les pratiques numériques ouvertes relationnelles et participatives qui utilisent l’infrastructure du Web pour engager les apprenants dans l’abondance de connaissances. D’autre part, la datafication de l’enseignement supérieur et l’enfermement résultant des plateformes sur lesquelles se produisent les pratiques ouvertes, par des entreprises extractrices de données et même prédatrices. La session examinera comment l’essor des outils basés sur les données et de l’IA exige une réponse critique et éthique, mais une réponse que notre culture contemporaine du « clic oui » rend extrêmement difficile à mettre en place. Il décrira les logiques de capture du marché et de battage médiatique qui façonnent actuellement les récits autour des outils numériques, et les obstacles que cela crée pour le développement de données authentiques, critiques et agentielles et de connaissances en IA parmi les professeurs et les étudiants.

La session est conçue pour soulever des questions plutôt que pour offrir des réponses, mais mettra en évidence deux projets de classe numérique actuels que le présentateur utilise pour tenter de combler les tensions mentionnées ci-dessus. Ces projets visent à favoriser les pratiques ouvertes et la littératie des données chez les futurs enseignants, et à les encourager à voir leur rôle de travailleurs du savoir sous un nouveau jour. La conférence invitera les participants à considérer notre responsabilité mutuelle – quoique toujours différentielle – d’aborder l’éducation numérique et ouverte avec un regard critique sur les écosystèmes numériques complexes et souvent potentiellement dangereux sur lesquels elle repose, tout en visant toujours à favoriser des espaces d’apprentissage participatif, ouverts partage et changement. En fin de compte, cela demandera une approche éthique de la datafication à l’échelle du secteur et invitera des commentaires sur ce à quoi cela pourrait ressembler.

</p>
</details>
```

### Séance parallèle 10.2 {-}

<mark>**Life Sciences Building LSB 105**</mark>

<mark>[**Lien de session**](https://uvic.zoom.us/j/82916752574?pwd=OG90Z0FwcjNkbmpvY2ZKYzRCVVQ5Zz09){target="_blank"}</mark>

```{block, type='speaker'}

#### GO-GN (Global OER Graduate Network) Panel {-} 

*Recherche à la limite de l’ouverture : Réflexions des membres de GO-GN*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
GO-GN, le Global OER Graduate Network, rassemble un noyau de doctorants actuels travaillant sur des sujets d’éducation ouverte, ainsi que l’équipe GO-GN de l’Open University, des anciens, d’autres chercheurs et d’autres voyageurs à travers l’espace ouvert. Et même si nous voyageons sans uniformes ni transporteurs, comme les membres des GO-GNers de Starfleet, nous allons audacieusement, essayant de repousser les limites de la connaissance sur le terrain. Reconnaissant les multiples sens dans lesquels l’éducation peut être ouverte, nous abordons le concept d’ouverture sous différents angles et utilisons une gamme de méthodes.

Dans cette table ronde, les membres du réseau réfléchiront sur le quoi, le pourquoi et le comment de leurs parcours doctoraux, et inviteront les participants à la session dans notre conversation.

</p>
</details>
```

## Séance simultanée 11 |  2:30-3:00 {-}

30 Minutes

### Séance simultanée 11.1 |  Caractère générique {-}

<mark>**Life Sciences Building LSB 101**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa)**</mark>

```{block, type='session'}


#### 2:30-3:00 | **Un livre électronique à soi** |  Pratique {-}

***Terry Greene & Christian Metaxes*** | *Trent University*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
La prolifération des technologies numériques a créé une multitude d’opportunités pour l’enseignement, l’apprentissage et la recherche dans l’enseignement supérieur. Cependant, de nombreux établissements n’ont pas pleinement adopté ces technologies pour permettre à leurs professeurs et étudiants de créer, de collaborer et de partager leur travail en ligne. Une combinaison de Domain of One’s Own et de Pressbooks peut offrir une solution à ce problème en fournissant aux professeurs et aux étudiants les outils et la structure dont ils ont besoin pour créer et publier en ligne d’une manière à la fois sécurisée, évolutive et accessible à tous. mais le plus fluide numériquement.
Dans cette présentation, nous explorerons les avantages de combiner la pratique de Domain of One’s Own avec l’utilisation d’une instance institutionnelle de Pressbooks. Ces avantages comprennent :
–	Fournir aux professeurs et aux étudiants une plate-forme pour créer et partager leur travail en ligne d’une manière qui met l’accent sur la facilité d’utilisation.
–	Permettre aux professeurs et aux étudiants de prendre le contrôle de leur apprentissage en créant un livre électronique personnel qui reflète la croissance de leur apprentissage tout au long de leur programme.
–	Permettre aux professeurs de créer et de publier des ressources éducatives ouvertes (REL) et d’autres ressources numériques pouvant être utilisées par les étudiants et d’autres éducateurs du monde entier.
–	Soutenir la création de communautés de pratique et de collaboration en ligne, où les professeurs et les étudiants peuvent partager leur travail, échanger des idées et fournir des commentaires.
La présentation s’adressera aux professeurs, aux concepteurs pédagogiques, aux bibliothécaires et aux technologues en éducation qui souhaitent explorer cette approche de l’enseignement, de l’apprentissage et de la recherche. Les participants découvriront les avantages de simplifier Domain of One’s Own avec Pressbooks.


</p>
</details>
```

### Séance simultanée 11.2 |  Formations d’apprentissage et d’enseignement en ligne {-}

<mark>**Life Sciences Building LSB 107**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa_2)**</mark>

```{block, type='session'}

#### 2:30-3:00 | **Impact de l’enseignement à distance d’urgence et de l’utilisation de la technologie numérique dans la pratique des enseignants de la maternelle à la 12e année** |  Recherche {-}

***Amber Hartwell*** | *University of Calgary*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Les technologies numériques sont potentiellement plus utilisées dans les classes de la maternelle à la 12e année qu’avant la pandémie de COVID-19. Afin de ralentir la propagation du virus, de nombreuses écoles sont brusquement passées à l’enseignement à distance d’urgence (ERT). Tous les enseignants et élèves n’étaient pas familiarisés avec l’utilisation de ces outils, mais ils ont dû s’adapter. COVID-19 a donné lieu à une grande quantité de recherches en éducation; cependant, les études axées sur l’ERT et son impact sur la pratique des enseignants sont limitées. Cette enquête explore l’impact de l’ERT sur l’utilisation de la technologie numérique dans la pratique actuelle des enseignants de la maternelle à la 12e année. Les données ont été recueillies auprès d’enseignants de la maternelle à la 12e année inscrits à des programmes d’études supérieures dans une grande université par le biais d’un questionnaire en ligne, d’entretiens semi-structurés, d’un examen des documents fournis par les participants aux entretiens et de notes analytiques. L’analyse et l’interprétation des résultats sont en cours et seront organisées en examinant les questions de recherche clés à travers la théorie de l’activité historique culturelle. Cette recherche révélera également les technologies numériques introduites au cours de l’ERT et les facteurs influençant la décision d’un enseignant d’intégrer les nouvelles technologies dans la pratique actuelle. L’auteur conclura en offrant des recommandations qui peuvent être utiles dans le travail de changement technologique dans l’enseignement de la maternelle à la 12e année.

</p>
</details>
```

### Séance simultanée 11.3 |  Maintenir un changement positif {-}

<mark>**Life Sciences Building LSB 103**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa_3)**</mark>

```{block, type='session'}

#### 2:30-3:00 | **Risques liés aux données sur les plateformes de classe en ligne : une analyse comparative des documents de politique** |  Recherche {-}

***Thi Kim, Thu Le & Bonnie Stewart*** | *University of Windsor*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Les plateformes de visioconférence en ligne ont été largement utilisées comme outils de classe clés dans le monde entier. Dans le sillage de la réponse de l’enseignement à distance d’urgence (ERT) à COVID-19, cependant, les problèmes de risque et de confidentialité des données que ces outils soulèvent dans les contextes de classe ont été peu abordés pour les chercheurs, les éducateurs et les étudiants. De plus, alors que l’expérience de pivot en ligne de l’ERT était généralement mondiale, les outils de classe numérique et leur provenance varient. De nombreuses plateformes technologiques éducatives sont développées aux États-Unis mais utilisées dans d’autres pays et juridictions. Pourtant, de multiples marchés de technologies éducatives alternatives existent dans le monde contemporain. Ce document a été conçu pour explorer si des revendications mondiales sur les risques potentiels pour la vie privée des outils de classe pourraient être faites et vise à analyser les documents de politique de deux outils populaires sur des marchés distincts : Zoom, développé aux États-Unis, et ClassIn, développé en Chine. Le document fournit une brève comparaison des risques relatifs aux données de ces deux principales plates-formes de classe en ligne. Les similitudes et les distinctions entre les deux en termes de transparence, de sûreté, de sécurité, de protection, de droits et de contextes des données sont décrites, mais dans l’ensemble, pour les besoins des éducateurs, les résultats suggèrent que les implications de Zoom et ClassIn sur la confidentialité des données sont plus similaires qu’elles ne le sont différent.

</p>
</details>
```

### Séance simultanée 11.4 |  Formations d’apprentissage et d’enseignement en ligne  {-}

<mark>Cette session a été reportée de la session 3.4</mark>

<mark>**Life Sciences Building LSB 105**</mark>


<mark>[**Session Link**](https://uvic.zoom.us/j/81832796337?pwd=d2lkclVtby9lZUo3QkZMR2V5RzFKdz09){target="_blank"}</mark>

```{block, type='session'}

#### 2:30- 3:00 | **Face à face, en ligne ou quelque chose entre les deux – Perceptions des étudiants sur l’engagement des étudiants dans différents environnements d’apprentissage** |  Recherche {-}

***Hongran Cui, Michelle Harrison & Victoria Handford*** | *Thompson Rivers University*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Pendant la pandémie de COVID-19, l’enseignement et l’apprentissage en ligne sont devenus le principal modèle d’éducation, et nous appelons cela l’enseignement à distance d’urgence (ERE) (Bozkurt et al., 2020). Des études antérieures ont accumulé de riches théories et ont prouvé que l’engagement étudiant (ES) est positivement lié à la réussite scolaire de l’étudiant. Cependant, seules quelques études se sont spécifiquement concentrées sur SE dans l’ERE, ce qui constitue une lacune dans la recherche. Cette recherche a révélé qu’il y avait des différences dans l’engagement des étudiants entre F2F et ERE ; les principales raisons à l’origine des différences étaient la conception et l’organisation des cours, l’apprentissage avec les pairs, l’interaction étudiant-professeur et l’interaction sociale. Les étudiants préféraient les cours synchrones et percevaient subjectivement moins d’interaction avec les instructeurs et les pairs. Cependant, un environnement favorable qui a été inclus dans l’engagement des étudiants dans l’apprentissage F2F mais qui n’est pas considéré comme un facteur influencé dans le modèle de communauté d’enquête s’est révélé dans cette étude comme un facteur constructif dans l’ERE. Sharma et Alvi (2021) ont constaté que les élèves étaient plus favorables à l’apprentissage mixte après la pandémie. Les résultats de cette étude fournissent la raison et le fondement théorique de la modification de l’éducation en ligne.

</p>
</details>
```
<mark>Cette session a été reportée de la session 3.5.</mark>


## Pause avec café et collation fournis | 3:00-3:30 {-}

## Séance simultanée 12 |  3:30-5:00 {-}

1.5 heures

### Séance simultanée 12.1 |  Formations d’apprentissage et d’enseignement en ligne {-}

<mark>**Life Sciences Building LSB 105**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa)**</mark>

```{block, type='session'}

#### 3:30-4:30 | **L’apprentissage intégré au travail numérique – l’impact de l’éducation sur la pénurie de main-d’œuvre (en français)** |  Pratique {-}

***Andrea Krasznai*** | *eCampusOntario*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
On parle souvent de pénurie de main-d’oeuvre, mais quelles sont les solutions? eCampusOntario propose un projet d’apprentissage intégré au travail (AIT), et en particulier d’AIT numérique, comme l’une des solutions pour combler cette lacune de compétences sur le marché du travail.

Le projet d’AIT d’eCampusOntario, le Consortium d’apprentissage expérientiel francophone de l’Ontario (CAPFO), rassemble des établissements postsecondaires francophones et bilingues de l’Ontario pour offrir des possibilités d’apprentissage expérientiel aux étudiants francophones. Cela comble une autre lacune vécue par la communauté francophone de l’Ontario, soit le manque d’occasions d’apprentissage par l’expérience dans les milieux francophones et bilingues. Une fois le match effectué sur la plateforme, les parties prenantes ont accès à des outils intégrés de gestion de projet et de communication, qui facilitent la collaboration. Bien que ce projet s’adresse spécifiquement à ces institutions, les possibilités sont infinies et sans frontières permettant aux étudiants de vivre une expérience enrichissante et diversifiée, et d’autre part, les employeurs du monde entier ont accès à la prochaine génération de talents.

Les enseignants et les employeurs ont désormais une chance égale de devenir des acteurs majeurs pour combler le fossé entre la théorie et la pratique, l’éducation et le travail.

</p>
</details>
```

```{block, type='session'}

#### 4:30-5:00 | **Ouvrir à la croisée des chemins : forger des voies de littératie médiatique et numérique** |  Recherche {-}

***Helen DeWaard*** | *Lakehead University & University of British Columbia*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Afin de repenser l’éducation ouverte et en ligne, et de répondre au thème de la conférence Reckonings and Reimaginings, cette session se concentrera sur les comptes rendus avec les technologies numériques et la production médiatique dans les facultés d’éducation canadiennes pour soutenir une vision des écosphères d’apprentissage ouvert tout en réimaginant Marshall Les paroles prophétiques de McLuhan « le médium est le message » (McLuhan, 1977). À l’heure actuelle, les éducateurs des espaces éducatifs ouverts et en ligne se trouvent à la croisée des chemins, face aux orientations et aux voies des médias et du numérique vers des avenirs incertains. Cette présentation commencera par explorer les assemblages passés de définitions et de pratiques des médias et de la littératie numérique qui ont un impact sur les décisions de naviguer au grand jour. Ensuite, les futurs possibles pour l’éducation en ligne sont partagés. Le présentateur fournit des perspectives et des orientations vers les possibilités émergeant de sa recherche. La session se terminera par une activité de cartographie et d’orientation collaborative et participative pour étudier les voies potentielles vers la création de nouveaux médias et de pistes numériques tout en explorant ensemble des écologies ouvertes inexplorées.

</p>
</details>
```



### Séance simultanée 12.2 |  Caractère générique {-}

<mark>**Life Sciences Building LSB 107**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa_2)**</mark>

```{block, type='session'}

#### 3:30-4:00 | **Simulations de réalité virtuelle dans les cours de sciences de l’enseignement supérieur : engagement des étudiants et développement professionnel des enseignants** |  Recherche {-}

***Sebastien Wall-Lacelle, Bruno Poellhuber*** | *Université de Montréal*

***Christine Marquis*** | *Cégep de Saint-Jérôme*

***Normand Roy*** | *Université de Montréal*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Alors que la littérature fait état d’une diminution de l’intérêt, de la motivation et de l’engagement des étudiants dans les cours de sciences, le besoin d’étudier des outils pédagogiques innovants est plus important que jamais. La réalité virtuelle offre la possibilité de voir et d’interagir avec des concepts invisibles ou inaccessibles de manière à ce que les élèves participent activement à leur apprentissage et il a été démontré qu’ils contribuent positivement à la motivation, à l’engagement et à l’apprentissage. Cependant, ces effets dépendent fortement du scénario pédagogique. Dans cette conférence, nous présenterons les résultats d’une recherche basée sur le design à grande échelle qui a réuni 38 enseignants et 5 579 étudiants. À l’aide de modèles de régression multiniveaux, nous avons observé que le niveau de complexité du scénario pédagogique est un prédicteur significatif de niveau 2 de l’engagement comportemental. Les pratiques pédagogiques associées à des scénarios pédagogiques de haute qualité seront mises en contraste avec des pratiques associées à des scénarios pédagogiques de faible qualité et les résultats d’entretiens qualitatifs avec des étudiants. De plus, nous présenterons une étude multicas sur le développement professionnel qui montre que les enseignants participant au projet ont rapporté des changements significatifs dans leur pratique pédagogique survenant au fil du temps convergeant vers la scénarisation pédagogique et l’apprentissage actif.

</p>
</details>
```

```{block, type='session'}

#### 4:30-5:00 | **Un cadre de conception ludique pour améliorer la motivation et l’engagement des apprenants L2** |  Recherche {-}

***Mourad Majdoub*** | *Université Laval*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
La gamification a fait l’objet de recherches approfondies car elle permet potentiellement aux apprenants de langues secondes/étrangères d’améliorer leur apprentissage des langues et, en même temps, de favoriser leur motivation et leur engagement (Koivisto & Hamari, 2019). La raison en est que plusieurs éléments de jeu, intégrés dans les environnements ludiques, peuvent accroître l’intérêt des apprenants, réduire leur anxiété et leur peur de parler une langue étrangère devant les autres, et enfin les encourager à adopter un type de comportement d’apprentissage favorable ( Dehghanzadeh et al., 2021). Étant donné que la gamification est un concept relativement nouveau et que la plupart des cadres de conception gamifiés suggérés ne reposent pas sur des bases théoriques solides, il n’est pas encore possible de comprendre pleinement son effet sur le processus d’apprentissage de la L2. Ainsi, la présente communication vise à identifier un cadre de conception ludique qui améliorerait la motivation et l’engagement des apprenants dans leurs cours de L2. Nous avons mené une expérience gamifiée L2 avec des élèves du secondaire où ils ont été observés en train d’interagir avec leur professeur et leurs pairs. Les notes de terrain et un entretien de groupe de discussion de suivi seront analysés qualitativement pour suggérer un cadre de conception pour l’apprentissage ludique de la L2. Les résultats préliminaires seront disponibles au printemps 2023 et seront partagés lors de la conférence OTESSA.

</p>
</details>
```

### Séance simultanée 12.3 |  Maintenir un changement positif {-}

<mark>**Life Sciences Building LSB 101**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa_3)**</mark>

```{block, type='session'}

#### 3:30-4:30 | **Re/storying Pédagogie pour l’université postnumérique : examiner le pouvoir de la narration critique pour imaginer un avenir meilleur** |  Pratique {-}

***Danielle Dilkes*** | *Western University*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
L’éducation dans le monde post-numérique remet en question les idées existantes sur les identités et les pratiques des instructeurs et des apprenants. Malgré les demandes institutionnelles de « retour à la normale », il n’y a pas de retour en arrière. Il n’y a qu’à aller de l’avant. Nous sommes à un tournant dans la définition de ce que pourrait être l’avenir de l’éducation. Ce futur est-il sombre et dystopique ? Ou s’agit-il d’espoir et de changement radical ?

Cette session invite les instructeurs, le personnel académique, les étudiants ou d’autres personnes impliquées dans la pratique relationnelle de l’enseignement et de l’apprentissage à réfléchir, remettre en question et réécrire les histoires qui façonnent les pratiques émergentes en éducation. Nous examinerons comment l’identité et la pédagogie sont complexes et sociomatérielles, à l’instar d’un jeu de Cat’s Cradle, composé de multiples brins, nœuds et tensions (Haraway, 1994). En utilisant la narration enchevêtrée, nous explorerons ce réseau d’influences nouées, révélant des valeurs, des motivations et des hypothèses cachées dans l’éducation. Nous nous engagerons ensuite dans une narration spéculative en réfléchissant à ce qui pourrait arriver si nous coupons un fil ou dénouons un nœud, ou si un nouveau nœud est noué ou si plusieurs brins sont introduits. En s’engageant dans une narration à la fois enchevêtrée et spéculative, cette session ouvrira de nouvelles façons de penser et de pratiquer l’éducation.

</p>
</details>
```



### Séance simultanée 12.4 |  Maintenir un changement positif {-}

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa_4)**</mark>

<mark>**Life Sciences Building LSB 103**</mark>

```{block, type='session'}

#### 3:30-4:00 | **Examen des forces et des défis de l’évaluation par les pairs** |  Recherche {-}

***Connie Blomgren*** | *Athabasca University*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Outre de nombreux autres aspects de la recherche et de l’académie, il y a une discussion sur le rôle, la fonction, les forces et les défis de l’examen par les pairs. Bien que l’examen par les pairs en double aveugle soit le processus le plus accepté pour les soumissions aux revues de recherche, des changements sont en cours. En plus des revues ouvertes, d’autres changements sont expérimentés avec diverses revues. Avec les progrès de l’intelligence artificielle et les implications pour toutes les formes d’écriture, y compris les documents savants, il est opportun de réévaluer les forces et les défis de l’examen par les pairs. Considérée dans le cadre de la pédagogie ouverte de Hegarty et des articles en libre accès comme un type de ressource éducative libre, l’évaluation par les pairs joue un rôle plus complexe dans le mouvement vers le changement éducatif.

</p>
</details>
```

```{block, type='session'}

#### 4:00-4:30 | **Un examen de la recherche sur l’adoption de l’éducation ouverte dans l’enseignement supérieur : exploration des approches, de la préparation et des méthodes d’évaluation** |  Recherche {-}

***Michael Paskevicius & Valerie Irvine*** | *University of Victoria*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
L’Université de Victoria a récemment reçu un financement interne pour développer le UVic Open Hub. Il s’agira d’un portail pour favoriser une communauté afin de soutenir le dialogue, la collaboration et les initiatives d’éducation ouverte sur le campus, y compris les ressources d’enseignement et d’apprentissage ouvertes, le partage d’approches d’enseignement ouvert et l’érudition ouverte. Comme l’UVic n’est pas le premier à s’engager dans un tel projet, nous partagerons les résultats d’une revue de la littérature qui explore a) les approches institutionnelles pour étendre l’adoption de l’éducation ouverte, b) la volonté du corps professoral à s’engager dans l’enseignement ouvert et c) les méthodes d’évaluation utilisées. pour mesurer l’impact. De plus, nous espérons inciter le public à apprendre comment il a vécu des initiatives institutionnelles en faveur de l’éducation ouverte et développer en collaboration un ensemble de stratégies et d’approches de partage.

L’objectif de l’UVic Open Hub est de changer la culture pour accroître la disponibilité, l’accès, la réutilisation et la redistribution des artefacts de connaissances et de soutenir la participation des parties prenantes, y compris les étudiants de premier cycle et des cycles supérieurs, le personnel, les professeurs et les administrateurs, dans des domaines couvrant la recherche. (accès ouvert, bourses d’études ouvertes, données ouvertes), enseignement et apprentissage (éducation ouverte, pédagogie ouverte, ressources éducatives ouvertes) et service (connexion de pratiques ouvertes pour l’engagement communautaire, le marketing et le recrutement). En adoptant une approche expansive qui va au-delà de la création et de l’adoption de ressources éducatives ouvertes, nous espérons développer une culture d’érudition ouverte en utilisant une approche ascendante en s’engageant avec des unités académiques individuelles.

</p>
</details>
```

```{block, type='session'}


#### 4:30-5:00 | **Recherche ? Quelle Recherche ? Technologie, évaluation et enseignement supérieur en tension** |  Recherche {-}

***Colin Madland*** | *University of Victoria*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
En utilisant la théorie de l’apprentissage médiatisé par la technologie de Bower comme cadre, les participants seront invités à s’engager dans une conversation générative sur les approches possibles pour résoudre le problème des corpus de littérature fragmentés et cloisonnés liés à l’évaluation intégrée à la technologie dans l’enseignement supérieur. Les pratiques d’évaluation intégrées à la technologie dans l’enseignement supérieur font l’objet d’un examen minutieux avec une autre « menace existentielle » sous la forme de la génération automatisée de textes. Pour ceux dont les disciplines nécessitent une écriture ou un codage approfondi, cela a conduit à une certaine lamentation concernant ce qui semble être à risque : la capacité de croire que les apprenants se sont engagés dans le travail cognitif de création de sens et présentent les résultats de ce travail. Dans mes propres observations et dans le processus d’examen de la littérature sur l’évaluation intégrée de la technologie dans l’enseignement supérieur, les réponses à ce développement semblent correspondre à des corpus de littérature distincts avec de faibles liens entre eux. Les réponses semblent être orientées vers la technologie, les approches d’évaluation ou les perspectives disciplinaires individuelles. Les liens entre ces corpus de littérature cloisonnés et les difficultés sur le terrain à réagir aux défis de l’évaluation intégrée à la technologie dans l’enseignement supérieur seront problématisés et explorés et les participants engageront une conversation pour susciter et maintenir un changement positif pour le bien de l’académie. et la société.

</p>
</details>
```

## Voir la programmation du Congrès pour les tentes sociales et les options alimentaires | 5:00-7:00 {-}

## OTESSA Social – Hall du bâtiment des sciences de la vie | 7:00-11:59 {-}
