# Mercredi 31 Mai 2023 | En Personne À L’Université York


```{block, type='protip'}

#### Rejoignez-nous à l’émission de radio matinale #OTESSA23 lundi, mardi, mercredi 29 30 31 mai de 6h30 à 7h30 (heure de l’Est) à [https://voiced.ca](https://voiced.ca){target="_blank"}
```

### Session Types {-}

```{block, type='protip'}


#### ✨ Note{-}

***All times are in Eastern Time (Canada)***
```

```{block, type='keynote'}

#### Keynote

```

```{block, type='speaker'}

#### Invited Speaker

```

```{block, type='session'}


#### Regular Session

```

```{block, type='social'}

#### Social Session

```

```{block, type='vendor'}


#### Vendor

```

```{block, type='workshop'}


#### Workshop

```

---

## Petit-déjeuner continental fourni | 8:00-9:00 {-}

## Bureau d’accueil ouvert | 8:00 - 11:30 {-}

## Bienvenue à la conférence, annonces et reconnaissance des terres | 9:00-9:15 {-}

<mark>**Life Sciences Building LSB 103**</mark>


## Casser | 9:15-9:30 {-}

## Séance simultanée 13 | 9:30-10:30 {-}

1 Hour

### Séance simultanée 13.1 |  Formations d’apprentissage et d’enseignement en ligne {-}

<mark>**Life Sciences Building LSB 103**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa)**</mark>

```{block, type='session'}


#### 9:30-10:00 | **Conception de travaux de groupe dans des cours en ligne pour développer les compétences de collaboration professionnelle des enseignants en formation** |  Recherche {-}

***Amber Hartwell, Christy Thomas, Barbara Brown & Bruna Nogueria*** | *University of Calgary*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Les établissements d’enseignement postsecondaire offrant de plus en plus de cours en ligne, il y a beaucoup à apprendre sur la conception du travail de groupe en ligne. Ceci est particulièrement important pour les cours de certification professionnelle où le travail de groupe est utilisé pour développer les compétences nécessaires pour préparer les étudiants à leur domaine de prédilection, comme l’enseignement K-12. Dans le cadre de la recherche d’études de cas, les auteurs synthétisent les résultats recueillis auprès d’enseignants et d’étudiants d’établissements postsecondaires de l’Ouest canadien offrant des cours en ligne dans le cadre de leurs parcours menant à un baccalauréat en éducation. Cherchant à comprendre comment le travail de groupe peut être conçu pour développer les compétences professionnelles essentielles requises dans la profession enseignante grâce à la prestation de cours en ligne, des données ont été recueillies au moyen d’une enquête en ligne, d’entretiens semi-structurés et de documents de cours. Les résultats suggèrent quatre considérations de conception pour le travail de groupe en ligne : (1) articuler clairement l’objectif du travail de groupe, (2) fournir un soutien à l’apprenant grâce à la présence de l’enseignant, (3) être intentionnel dans la manière dont les groupes sont établis et (4) tirer parti des outils numériques pour collaboration. Les résultats permettront aux professeurs, aux étudiants et aux responsables des politiques éducatives de comprendre comment l’apprentissage en groupe dans les cours en ligne peut être conçu pour développer des compétences professionnelles essentielles. Cela profitera particulièrement aux établissements d’enseignement postsecondaire offrant des cours en ligne dans des domaines professionnels.

</p>
</details>
```

```{block, type='session'}


#### 10:00-10:30 | **Le paysage des modalités de fusion** |  Pratique {-}

***Valerie Irvine*** | *University of Victoria*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Sur le campus de l’enseignement supérieur d’aujourd’hui, il y a probablement une douzaine de nouveaux termes utilisés pour décrire différentes configurations autour de la modalité des cours. La modalité fait généralement référence au lieu et au moment des interactions. Ce qui était autrefois un simple binôme de face à face ou en ligne est maintenant devenu si extrêmement complexe que notre capacité à nous comprendre est altérée. Dans cette session, je discuterai d’un article récent que j’ai publié dans la revue Educause, intitulé Le paysage des modalités de fusion, y compris l’histoire de la modalité, la terminologie de la modalité de fusion, les luttes avec la sémantique et la pédagogie contre la modalité. Je terminerai par des mesures pratiques que les individus et les établissements peuvent prendre pour prendre des décisions solides en matière de planification et de pédagogie qui tiennent également compte de la charge de travail de l’instructeur et de l’attention portée à l’apprenant.

</p>
</details>
```

### Séance simultanée 13.2 |  Aborder les inégalités {-}

<mark>**Life Sciences Building LSB 101**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa_2)**</mark>

```{block, type='workshop'}


#### 9:30-10:30 | **Les étudiants en tant que concepteurs experts de cours sur l’équité : la nouvelle normalité à l’ère post-numérique** |  Workshop {-}

***Lorayne Robertson*** | *Ontario Tech University*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Les complexités de la condition humaine sont indéniables, y compris les différences infinies entre les gens. Lorsque la différence se traduit par une diminution de l’accès, de la participation et des résultats, ces inégalités doivent être comprises afin d’être traitées, en particulier dans les écoles. À l’ère post-numérique, la surveillance a permis d’enregistrer et de distribuer les injustices, sensibilisant de manière aiguë aux nombreuses formes d’oppression systémique dans la société canadienne. Pour ces raisons, l’étude de l’équité, de la diversité et de l’inclusion (EDI) est importante dans l’enseignement postsecondaire, car le programme de la maternelle à la 12e année dans les écoles canadiennes peut être muet sur certains de ces sujets. Les concepteurs de cours en EDI doivent impliquer à la fois les étudiants qui sont déjà conscients que l’éducation et la société sont inégales et ceux qui ne le sont pas. Tout au long du processus d’apprentissage des aspects inégaux de l’éducation, il peut être difficile de maintenir l’engagement des élèves. En outre, les concepteurs de cours EDI doivent enseigner l’EDI de manière à ce que les concepts, théories et discours clés dans les domaines de différence s’unissent pour donner un sens et renforcer l’apprentissage.

Dans cette session, les étudiants qui ont conçu des cours de base en EDI aux cycles supérieurs et de premier cycle pour leur faculté d’éducation abordent les différents antécédents, perspectives et objectifs qu’ils ont apportés au processus de conception de cours. En co-créant le cours, ils se sont rendus compte qu’il y avait plusieurs domaines d’oppression et ont dû se demander quels domaines traiter en premier. Différentes approches théoriques de l’enseignement de l’EDI dans le passé ont créé des espaces séparés plutôt que des compréhensions communes de l’inégalité. Il est peu probable que l’étude de la théorie critique de la race ouvre des espaces pour une expression de genre plus large. Une compréhension de l’intersectionnalité peut apporter une prise de conscience des effets cumulatifs lorsque les sites d’oppression se croisent, mais elle est insuffisante en tant qu’approche pédagogique pour aborder toutes les façons dont les élèves peuvent être « altérés » dans un système scolaire. Cela a créé un défi pour les étudiants concepteurs de discerner en quoi les domaines d’inégalité dans les écoles étaient similaires et en quoi ils différaient.

Travaillant dans le cadre d’un programme éducatif axé sur le numérique, les étudiants ont travaillé ensemble pour créer des cours en ligne. Ils ont cherché des moyens de renforcer la présence sociale et la présence cognitive au sein de l’espace en ligne. Ils ont réalisé que l’enseignement de l’EDI n’est pas un processus de conversion mais un processus d’écoute d’autres perspectives et de compréhension des inégalités éducatives à travers les yeux des autres. Certains avaient vécu des iniquités en tant que membres de groupes recherchant l’équité; d’autres acceptaient de comprendre les formes systématiques d’oppression ; et d’autres encore voulaient travailler vers des approches pédagogiques critiques, décolonisatrices et transformatrices. En tant que groupe, ils ont développé une compréhension collective de ce qui est nécessaire pour préparer les étudiants à comprendre comment les lieux de travail et les écoles du Canada peuvent devenir des sites de sensibilisation et de changement accrus en matière d’EDI.

</p>
</details>
```

### Séance simultanée 13.3 |  Formations d’apprentissage et d’enseignement en ligne {-}

<mark>**Life Sciences Building LSB 107**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa_3)**</mark>

```{block, type='session'}


#### 9:30-10:00 | **Tests collaboratifs en ligne : conception et mise en œuvre dans un grand cours de premier cycle de première année** |  Pratique {-}

***Mariel Miller, Safoura Askari & Syed Qudsia*** | *University of Victoria*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Les tests collaboratifs en ligne sont une approche d’évaluation qui met l’accent sur l’apprentissage assisté par la technologie grâce à l’interaction avec les pairs. Alors que la pandémie de COVID-19 a entraîné une croissance exponentielle du travail d’équipe en ligne, les compétences pour la résolution collaborative de problèmes en ligne sont devenues essentielles pour les diplômés d’aujourd’hui. À ce titre, les tests collaboratifs en ligne peuvent jouer un rôle crucial pour aider les élèves à développer ces compétences. Dans cet article, nous rapportons comment un test collaboratif en ligne a été mis en œuvre dans un grand cours de premier cycle de première année. Nous commencerons par une revue de la littérature sur les tests collaboratifs en ligne. Nous décrivons ensuite comment l’équipe pédagogique a conçu et administré un examen de mi-session collaboratif en ligne synchrone dans lequel les groupes ont travaillé ensemble pour analyser un scénario de cas complexe. Enfin, nous conclurons par une réflexion sur les forces et les limites de notre approche et les opportunités de conception future.

</p>
</details>
```

```{block, type='session'}

#### 10:00-10:30 | **Curriculum caché des technologies de l’éducation** |  Pratique {-}

***Danielle Dilkes*** | *Western University*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Cette session offrira aux participants l’occasion de réfléchir aux espaces numériques dans lesquels l’apprentissage se produit et à la manière dont ces espaces contraignent et autorisent le comportement des étudiants et des instructeurs grâce à des conceptions qui incarnent de manière invisible des valeurs, des motivations, des croyances et des hypothèses spécifiques sur l’éducation. Nous examinerons différentes conceptions d’environnements d’apprentissage, y compris les conceptions carcérales, ou architectures hostiles, communes à de nombreuses technologies éducatives telles que les systèmes de gestion de l’apprentissage, les technologies de surveillance et d’autres outils numériques. Nous examinerons également les outils qui mettent l’accent sur l’autonomie de l’apprenant en permettant une répartition du contrôle et comment ces conceptions reflètent une croyance différente sur l’enseignement et l’apprentissage. Étant donné que de nombreuses valeurs et croyances intégrées dans ces conceptions sont cachées, nous examinerons comment certaines conceptions peuvent contrôler la façon dont les instructeurs enseignent, comment les apprenants apprennent et la relation entre les instructeurs et les apprenants. Nous conclurons par une discussion pragmatique sur la façon de trouver un équilibre entre la commodité de certaines technologies et l’importance de favoriser les littératies numériques nécessaires pour identifier les outils qui s’alignent sur nos propres idéologies et identités pédagogiques.

</p>
</details>
```
### Séance simultanée 13.4 |  Maintenir un changement positif {-}



<mark>**Life Sciences Building LSB 105**</mark>

```{block, type='session'}

#### 9:30- 10:30 | **Être(com)ing bibliothécaires OE en Ukraine en temps de guerre : éliminer les barrières linguistiques et pratiquer l’inclusion** |  Pratique {-}

***Paola Corti*** | *SPARC Europe*

***Tetiana Kolesnykova*** | *Ukrainian State University of Science and Technologies*

***Mira Buist- Zhuk*** | *University of Groningen*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Les bibliothécaires ukrainiens sont les champions du changement positif malgré la guerre en cours avec la Russie. La bibliothèque universitaire de l’Université d’État ukrainienne des sciences et technologies a continué à soutenir les étudiants et les professeurs, même en travaillant à distance depuis les sous-sols de la maison, en partageant des ordinateurs et en prenant soin des enfants des autres, malgré les alarmes anti-aériennes et l’électricité et le chauffage quotidiens. pannes. Cependant, ce n’est qu’une partie de leur travail. Ils saisissent toutes les occasions de faire avancer leur programme ouvert en améliorant leurs compétences grâce à l’apprentissage entre pairs, en participant à des réseaux internationaux et en adaptant les REL existantes et en créant de nouvelles. Ils construisent des ponts entre le présent et l’avenir : dès que cette guerre sera terminée, les bibliothécaires ukrainiens faciliteront de meilleures opportunités d’enseignement et d’apprentissage avec de nouvelles compétences professionnelles et des collaborations externes.

Tout cela en faisant face sans relâche aux problèmes linguistiques : rejeter les tentatives de « linguicide » de la Russie et travailler avec des collègues d’autres pays. Ce dernier incite la communauté internationale à apporter son soutien. Le premier nécessite une stratégie différente : les bibliothécaires ukrainiens travaillent activement à préserver la langue et le patrimoine de leur pays, en veillant à ce que son histoire et sa culture ne soient pas oubliées, malgré la guerre. Cette présentation offre l’opportunité d’entendre leur histoire et de construire de nouvelles voies de collaboration tout en renforçant celles qui existent déjà.

</p>
</details>
```

## Casser | 10:30-11:00 {-}

## Discours d’ouverture | 11:00-12:00 {-}

<mark>**Lassonde Building LAS C**</mark>


```{block, type='keynote'}
 

#### Faire progresser la vérité, faire face à la complaisance et libérer la possibilité de guérir par l’éducation  {-}

***Nick Bertrand*** | *University of Calgary*



<details>
<summary>**Abstract**</summary>
<p>

L’éducation en tant qu’outil de guérison et de réconciliation a évolué au fil des ans, et en particulier depuis la publication des 94 appels à l’action de la Commission de vérité et réconciliation. Huit ans plus tard, dans une société post-TRC, quelles vérités restent inconnues ? Quelles leçons avons-nous apprises en essayant de mobiliser un changement significatif ? Comment pouvons-nous, en tant qu’éducateurs, assumer nos responsabilités dans le travail de reconstruction de la relation brisée qui nous a amenés dans cet espace ? Alors que le pont de la réconciliation continue d’être construit, les systèmes éducatifs continueront de jouer un rôle clé dans le processus de sensibilisation, de compréhension et de création d’action.
</p>
</details>


##### [**Lien de session**](){target="_blank"} {-}

```

## Casser | 12:00-1:30 {-}

## Séance parallèle 14 | Session multi-accès   | 1:30-2:15 {-}

45 Minutes

### Séance parallèle 14.1 {-}

<mark>**Life Sciences Building LSB 103**</mark>


```{block, type='speaker'}

#### Valerie Irvine, OTESSA |  ***Session multi-accès*** {-} 

*Plaidoyer pour l’apprentissage numérique : contribution à la politique et au budget du gouvernement*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Au cours de cette session destinée aux participants en personne et en ligne, nous examinerons les options de plaidoyer gouvernemental, fournirons des exemples d’actions passées et décrirons les mesures que nous pouvons prendre à l’avenir pour créer un changement dans le soutien à l’éducation numérique, en ligne et ouverte.

Actuellement, nous manquons l’occasion d’avoir une voix collective alors que des changements de système se produisent qui ont un impact sur la conception et le soutien de l’éducation en ligne et ouverte. Je fournirai des exemples de différentes voies de plaidoyer, telles que des mémoires à la direction d’une institution ou d’un gouvernement provincial. J’examinerai le processus pour les soumissions prébudgétaires provinciales ou fédérales; comment examiner les lettres de mandat des leaders ministériels ; et invitez les participants à écrire ou à rencontrer votre représentant local (par exemple, député pour un représentant provincial ou député pour un représentant fédéral) pour amplifier le travail en cours.

Nous avons également une session le 2 juin concernant les changements nécessaires dans la tri-agence fédérale pour le financement de la recherche car il existe des préjugés systémiques contre l’éducation, sans parler de la technologie éducative. Après un aperçu de ces options, nous vous inviterons à apporter des idées qui formeront la soumission prébudgétaire fédérale d’OTESSA plus tard cet été.

</p>
</details>
```

## Casser | 2:15-2:30 {-}

## Séance simultanée 15 | 2:30-3:00 {-}

30 Minutes

### Séance simultanée 15.1 |  Aborder les inégalités {-}

<mark>**Life Sciences Building LSB 101**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa)**</mark>

```{block, type='session'}


#### 2:30-3:00 | **Pratiques éducatives ouvertes dans l’enseignement supérieur canadien en milieu francophone minoritaire : réflexions sur la justice linguistique** |  Recherche {-}

***Catherine Lachaîne*** | *University of Ottawa*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Au cours de cette session, je présenterai les résultats d’une étude exploratoire qualitative portant sur les pratiques pédagogiques actuelles des professeurs, bibliothécaires et chargés de cours postsecondaires en contexte francophone minoritaire au Canada afin de déterminer si ces pratiques sont conformes aux pratiques éducatives ouvertes (PEO). Notre principale question de recherche était : Dans quelle mesure, le cas échéant, les professeurs, bibliothécaires et chargés de cours postsecondaires adoptent-ils les OEP en milieu francophone minoritaire au Canada?

Trois thèmes ont été générés dans nos analyses thématiques. L’adoption ou la non-adoption des OEP en milieu francophone minoritaire au Canada semble être liée à 1) une connaissance et une application limitées des OEP, 2) un soutien inadéquat et 3) le potentiel des PEO au niveau postsecondaire en milieu francophone minoritaire . Les thèmes et sous-thèmes nous donnent un bon aperçu des enjeux d’insertion OEP présents au moment de l’étude, tant en termes de contexte sociolinguistique que de niveau de connaissance de l’éducation ouverte. Les voix des participants ont également souligné l’impact potentiel du mouvement d’ouverture en contexte linguistique minoritaire. Des recherches supplémentaires sur les groupes linguistiques marginalisés sont nécessaires pour explorer le potentiel de l’OEP à soutenir un changement inclusif, équitable et positif dans le paysage de l’éducation ouverte.Trois thèmes ont été générés dans nos analyses thématiques. L’adoption ou la non-adoption des OEP en milieu francophone minoritaire au Canada semble être liée à 1) une connaissance et une application limitées des OEP, 2) un soutien inadéquat et 3) le potentiel des PEO au niveau postsecondaire en milieu francophone minoritaire . Les thèmes et sous-thèmes nous donnent un bon aperçu des enjeux d’insertion OEP présents au moment de l’étude, tant en termes de contexte sociolinguistique que de niveau de connaissance de l’éducation ouverte. Les voix des participants ont également souligné l’impact potentiel du mouvement d’ouverture en contexte linguistique minoritaire. Des recherches supplémentaires sur les groupes linguistiques marginalisés sont nécessaires pour explorer le potentiel de l’OEP à soutenir un changement inclusif, équitable et positif dans le paysage de l’éducation ouverte.

</p>
</details>
```

### Séance simultanée 15.2 |  Aborder les inégalités {-}

<mark>**Life Sciences Building LSB 105**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa_2)**</mark>

```{block, type='session'}



#### 2:30-3:00 | **Les Effets d’une initiative pour brancher sur Internet les familles à faible revenu (en français)** |  Recherche {-}

***Normand Roy*** | *Université de Montréal*

***Valerie Irvine*** | *University of Victoria*

***Michele Jacobsen*** | *University of Calgary*

***Catherine Middleton*** | *Ryerson University* <!--{--change to new name?--}-->

***Simon Parent*** | *Université de Montréal*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Le gouvernement canadien a lancé l’initiative « Familles branchées » en 2018. L’objectif était de fournir un accès Internet aux familles à faible revenu partout au Canada. Au tournant du millénaire, Internet est devenu un outil incontournable pour accéder à l’information et au savoir. Pourtant, le Canada, comme de nombreux autres pays dans le monde, fait face à des défis en matière d’accessibilité pour de multiples raisons : géographie, culture, histoire, etc. (Howard et al., 2018). En ce sens, des écarts technologiques se sont développés en fonction de l’âge, de la langue, du revenu familial, de l’origine, etc. Howard et al. (2018) soulignent que l’éducation, l’âge et le revenu sont corrélés à un accès limité à Internet et à une faible littératie numérique. L’enquête diffusée consistait en 30 questions portant sur : les caractéristiques sociodémographiques, les ressources numériques accessibles, les habitudes avec la technologie, les besoins d’initiative, les usages et les défis d’Internet. Au total, 89 776 questionnaires (P1 = 28 444 ; P2 = 9 163 ; P3 = 34 327 ; P4 = 17 842) ont été remplis par les participants à l’initiative. En plus du questionnaire, des entretiens ont été menés à chaque phase avec un nombre variable de participants (entre 20 et 50) pour clarifier les idées. Les résultats longitudinaux mettent en lumière l’impact d’une telle initiative sur les familles à faible revenu, ainsi que les effets de la pandémie mondiale de COVID-19 sur les habitudes d’un groupe à risque.

</p>
</details>
```
### Séance simultanée 15.3 |  Maintenir un changement positif {-}

<mark>Cette session a été reportée de la session 3.5.</mark>



```{block, type='session'}

#### 2:30-3:00 | **Le rôle des bibliothèques universitaires dans la promotion de la littératie algorithmique dans les universités canadiennes : un métalalphabète** |  Recherche {-}

***Marta Samokishyn*** | *Saint Paul University*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Les algorithmes deviennent partie intégrante de notre écosystème socio-numérique : l’impact de Facebook sur les pratiques de vote, le filtrage des CV d’Amazon, les logiciels de profilage racial et même la possibilité d’obtenir un prêt. En conséquence, il est urgent d’aborder la question de la sensibilisation algorithmique et de la littératie algorithmique dans l’enseignement supérieur afin de promouvoir les compétences de pensée critique à l’égard des biais algorithmiques et de leur impact sur l’infrastructure sociale.

Cette présentation abordera la question de la littératie algorithmique du point de vue de la littératie informationnelle et de la métallittératie. Le présentateur discutera du rôle de l’éducation à la maîtrise de l’information dans la promotion de la sensibilisation algorithmique dans l’enseignement supérieur et abordera l’adoption de pratiques d’enseignement pour promouvoir une conscience critique sur les algorithmes dans les établissements postsecondaires au Canada

</p>
</details>
```


## Pause avec café et collation fournis | 3:00-3:30 {-}

## Séance simultanée 16 | 3:30-5:00 {-}

### Séance simultanée 16.1 |  Caractère générique {-}

<mark>**Life Sciences Building LSB 101**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa)**</mark>

```{block, type='session'}



#### 3:30-4:30 | **L’interconnectivité de l’héutagogie et de l’éducation 4.0 dans l’enseignement supérieur en ligne** |  Recherche {-}

***Jeanne Kim*** | *Athabasca University*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Les progrès technologiques de l’industrie 4.0 créent un monde dynamique et en évolution rapide qui affecte notre façon de vivre et de travailler. Les éducateurs doivent repenser les approches pédagogiques existantes afin de mieux préparer les apprenants aux futures carrières que l’industrie 4.0 créera. Le Forum économique mondial a défini un nouveau modèle d’éducation, appelé Education 4.0, qui contient huit changements majeurs pour redéfinir l’apprentissage dans la nouvelle économie. L’heutagogie, ou apprentissage autodéterminé, est une approche qui favorise la pensée critique, les compétences socio-émotionnelles et l’apprentissage tout au long de la vie. Ces compétences sont nécessaires pour l’Éducation 4.0. Le but de cet article est de recommander les principes de l’héutagogie comme approche efficace d’enseignement et d’apprentissage pour répondre aux besoins de l’éducation 4.0. L’approche de l’étude examine la littérature existante sur l’éducation 4.0 et l’heutagogie. Un modèle conceptuel qui relie l’héutagogie aux quatre principes d’apprentissage de l’éducation 4.0 sera proposé comme une découverte clé pour répondre à la question de recherche : comment l’héutagogie dans l’enseignement supérieur en ligne répond-elle aux besoins de l’éducation 4.0 ? Le document fournit une base pour de nouvelles recherches et discussions sur la manière dont l’héutagogie et d’autres approches peuvent répondre aux besoins de l’éducation 4.0 pour préparer les apprenants à un monde en mutation.

</p>
</details>
```

```{block, type='session'}



#### 4:30-5:00 | **Un cours entrelacé : pratique réflexive et portfolio** |  Pratique {-}

***Christine Ho Younghusband*** | *University of Northern British Columbia*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Un programme de formation des enseignants en Colombie-Britannique (C.-B.) a repensé le programme pour inclure un cours entrelacé qui s’étalerait sur les 16 mois du programme pour développer la pratique réflexive du candidat enseignant par le biais d’enquêtes et de portfolios électroniques. Le programme était auparavant un programme de 2 ans et offrait un cours EdTech de 3 crédits au troisième trimestre de quatre en tant que cours distinct. Dans ce cours, la création d’un e-Portfolio aurait été l’un des objectifs d’apprentissage. Dans ce cours entrelacé, cependant, les candidats enseignants sont exposés au développement d’un site WordPress open source au premier trimestre avec les conseils du corps professoral, mais au fil du temps, les candidats enseignants deviennent plus autonomes et indépendants avec la création de contenu à mesure qu’ils développent leur pratique réflexive, s’engagent dans une enquête sur un sujet d’intérêt pour l’éducation et établir des liens explicites entre la théorie et la pratique tout en répondant aux attentes des normes professionnelles pour les éducateurs de la Colombie-Britannique. Écrire à travers des blogs et créer des pages Web qui décrivent le mieux qui le candidat enseignant perçoit ses forces et ses compétences en tant qu’éducateur fournit une plate-forme pour personnaliser son apprentissage et son sens entre la théorie et la pratique.

</p>
</details>
```

### Séance simultanée 16.2 |  Caractère générique {-}

<mark>**Life Sciences Building LSB 105**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa_2)**</mark>

```{block, type='session'}

#### 3:30-4:30 | **Concevoir des parcours de développement de compétences agiles pour l’adaptation au climat : tirer parti des cadres de compétences ouverts et des ressources éducatives ouvertes pour développer des micro-certificats** |  Pratique {-}

***David Porter*** | *DP+Associates*

***Robin S Cox*** | *Royal Roads University*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Le renforcement des capacités pour faire progresser le leadership en matière de changement climatique est devenu une exigence essentielle en matière de développement de la main-d’œuvre, tant pour les professionnels que pour les travailleurs de première ligne. Comme l’a noté le rapport du Forum économique mondial sur l’emploi 2020 (2020), il est de plus en plus nécessaire de fournir des opportunités à court terme de reconversion et de perfectionnement qui ne diminueront pas à mesure que nous avancerons. Les micro-titres ont été proposés comme stratégie pour permettre le développement continu des connaissances et des compétences au sein de la main-d’œuvre, que nous examinons dans le contexte d’une initiative universitaire qui a prototypé des parcours de compétences pour aborder les thèmes clés de l’adaptation au climat, y compris l’utilisation des connaissances autochtones. et les visions du monde comme lentille critique pour l’analyse et l’action. Nous rapportons et discutons de l’utilisation stratégique du Cadre de compétences en adaptation climatique (2020) - un cadre de compétences ouvert sous licence CC - ainsi que de l’utilisation de ressources éducatives ouvertes pour créer des voies agiles vers le développement des compétences. Les parcours que nous avons conçus et que nous testons combinent des ressources d’apprentissage autonome, des activités individuelles et de groupe et des pratiques d’évaluation authentiques pour valider le développement des compétences. Les micro-titres sont décernés par une division universitaire d’apprentissage continu et professionnel à des professionnels de plusieurs domaines de pratique pour des démonstrations de compétence.

</p>
</details>
```

```{block, type='session'}



#### 4:30-5:00 | **Qu’est-il arrivé à OpenCourseWare ? Une discussion sur le passage du mouvement de l’éducation ouverte du contenu des cours aux manuels scolaires** |  Pratique {-}

***Erik Christiansen*** | *Mount Royal University*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Le mouvement de l’éducation ouverte a maintenant plus de vingt ans, si l’on compte depuis le lancement d’OpenCourseWare (OCW) du MIT en 2001. Bien que l’OCW ait contribué à relancer l’enthousiasme de l’enseignement supérieur pour les ressources éducatives libres (REL), les organismes de financement provinciaux ont doublé sur les manuels libres, et cet accent se reflète dans le langage utilisé par les organismes de financement provinciaux, ainsi que dans le nombre impressionnant et croissant de manuels sous licence libre. L’accent mis sur les manuels est compréhensible compte tenu de l’intérêt intense des étudiants. Plusieurs organismes de financement provinciaux, dont BC Campus, OpenEd Manitoba et eCampus Ontario, ont permis aux étudiants d’économiser des millions de dollars en encourageant l’adoption de manuels scolaires ouverts au niveau postsecondaire. De plus, les manuels ouverts (et autres objets d’apprentissage) sont sans doute plus faciles à héberger et à distribuer que des cours entiers. Le compromis est que cette focalisation déséquilibrée sur les manuels ouverts signifie que quelques institutions (notamment le MIT, la TU Delft et d’autres) dominent l’espace OCW. Dans cette présentation, l’auteur expliquera les raisons pour lesquelles l’investissement OCW est incohérent et soulignera les défis auxquels sont confrontés la création et l’adoption d’OCW. L’auteur soutiendra également que le recentrage sur les investissements d’OCW a le potentiel de renforcer la réputation institutionnelle et de satisfaire un public avide de contenu ouvert de haute qualité.

</p>
</details>
```

### Séance simultanée 16.3  |  Maintenir un changement positif {-}

<mark>**Life Sciences Building LSB 107**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa_3)**</mark>

```{block, type='session'}



#### 3:30-4:00 | **Ouvrir les plateformes numériques à la recherche communautaire** |  Recherche {-}

***Robyn Hall*** | *MacEwan University*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Les universités canadiennes s’efforcent de bâtir des fondations plus solides en matière d’engagement communautaire. Les chercheurs communautaires font ce travail fondamental, menant des recherches aux côtés de partenaires communautaires. Ce travail aboutit souvent à des résultats de recherche non traditionnels, notamment des rapports, des notes d’orientation, des expositions photographiques et des productions vidéo. Bien que ce travail serve à éclairer les politiques, à faire avancer le changement social et, par extension, à contribuer à l’enseignement et à l’apprentissage, il n’est souvent pas largement partagé en ligne de manière à encourager la découverte et l’utilisation à long terme. Notamment, il est souvent absent des plateformes numériques gérées par les bibliothèques universitaires utilisées pour distribuer des œuvres savantes et créatives de manière ouverte et durable, telles que les référentiels institutionnels et les applications de publication Web open source, et il est rarement partagé sous des licences flexibles de droits d’auteur Creative Commons. Réfléchissant aux données récentes recueillies par le biais d’enquêtes et d’entretiens avec des chercheurs et des bibliothécaires communautaires canadiens soutenant les communications savantes, cette présentation donnera un aperçu des raisons pour lesquelles ce travail n’est si souvent pas partagé sur des plateformes d’accès libre. Les participants seront invités à examiner les défis et les opportunités présents dans leurs propres institutions pour soutenir la diffusion des résultats de la recherche communautaire, avec un accent particulier sur la réinvention des services de bibliothèque universitaire pour aider à faire progresser son impact et sa portée.

</p>
</details>
```

```{block, type='session'}



#### 4:00-4:30 | **Le rôle de la littératie des enseignants en matière d’évaluation dans un environnement d’apprentissage fondé sur l’investigation** |  Recherche {-}

***Maryam Shirdel Pour & Michael Paskevicius*** | *University of Victoria*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
La littératie en matière d’évaluation est définie comme les connaissances et l’expertise qui sont utilisées pour effectuer des évaluations valides (Luthfiyyah et al., 2020). La recherche indique que la littératie des enseignants en matière d’évaluation pourrait influencer l’efficacité des pratiques éducatives (Oo et al., 2022). Les enseignants ayant une littératie d’évaluation adéquate aident les apprenants à améliorer leur compréhension et à atteindre les résultats d’apprentissage souhaités. L’apprentissage basé sur l’investigation est défini comme une approche pédagogique qui met l’accent sur l’action des étudiants et leur rôle actif dans la création de connaissances, souvent à l’aide d’outils et de technologies numériques. La création d’un environnement d’apprentissage qui encourage les apprenants à approfondir leurs connaissances à travers leurs enquêtes et à construire leur compréhension tout en participant à des activités d’apprentissage favorise l’apprentissage des élèves (Vaughn et al., 2022). L’évolution vers un apprentissage fondé sur l’investigation nécessite certains ajustements dans les approches que les éducateurs appliquent pour évaluer les apprenants lorsqu’ils documentent les progrès de leur apprentissage de manière ouverte. Les enseignants peuvent bénéficier du développement de la littératie en matière d’évaluation pour enseigner plus efficacement, répondre aux besoins éducatifs des apprenants et évaluer leur processus d’apprentissage. Le but de cet article est d’examiner la littérature existante afin de mieux comprendre l’influence de la littératie des enseignants en matière d’évaluation lors de la réalisation d’évaluations dans un environnement d’apprentissage basé sur la recherche et la technologie. De plus, les défis auxquels les enseignants peuvent être confrontés lors de la mise en œuvre de l’évaluation basée sur l’investigation seront discutés.

</p>
</details>
```

```{block, type='session'}



### Séance simultanée 16.4  |  Formations d’apprentissage et d’enseignement en ligne {-}


<mark>**Life Sciences Building LSB 103**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa_4)**</mark>

```{block, type='session'}

#### 3:30-5:00 | **Langage, narration et limites narratives de l’empire : approcher la ficelle comme outil pédagogique féministe** |  Atelier {-}

***Anna Lee-Popham*** | *University of Guelph*

***Aparajita Bhandari*** | *Cornell University*

***Sarah York-Bertram*** | *York University*

***Sarah Choukah*** | *Université de l'Ontario français*

***Laurence Butet-Roch*** | *York University*

<details>
<summary><b>Abstract</b></summary>
<p>
Suite à l’accent mis par la réunion sur la lutte contre les inégalités et le virage vers l’apprentissage virtuel, cet atelier présente aux participants Twine en tant qu’outil de narration interactif pour défaire de manière créative les structures du langage pour tenir compte des récits d’Empire. Les participants exploreront les applications interdisciplinaires de l’outil et créeront des histoires non linéaires. Du point de vue féministe, Twine est un outil numérique accessible et gratuit qui, en ayant une faible courbe d’apprentissage (Anthropy, Evans), « défie les standards traditionnels en renversant la célébration de la difficulté, à la fois dans la production et le jeu » (Harvey).

L’atelier explore Twine comme un outil pour penser autrement et façonner les possibilités futures, guidé par les questions : Comment Twine, en tant qu’outil de narration interactif, peut-il créer des opportunités pour les participants d’utiliser le mot écrit ? Comment ces engagements pourraient-ils permettre de nouveaux types d’expériences et de création de sens pour les apprenants ? Notre objectif est de faciliter l’exploration de la manière dont la non-linéarité peut refléter les formes féministes noires, anticoloniales et plurielles du futurisme et du design. Nous ne positionnons pas Twine comme une solution technologique, mais comme un outil pour générer une réflexion expansive ; s’engager dans une recherche numérique collaborative ; et créer de nouvelles significations. Nos animatrices puisent dans leurs domaines d’études et leurs perspectives pédagogiques (cultures numériques, communications, études de genre, féministes et féministes, écriture créative) pour démontrer les applications interdisciplinaires de l’outil.

</p>
</details>
```

## Réception du Président du Congrès | 5:00-7:00 {-}

<mark>**Scott Library – Atrium**</mark>

## OTESSA Social – Hall du bâtiment des sciences de la vie | 7:00-11:59 {-}
