# Vendredi 2 Juin 2023 | Séances En Ligne Uniquement

```{block, type='protip'}

#### Il n'y a pas d'émission de radio matinale #OTESSA23 aujourd'hui.
```

### Session Types {-}

```{block, type='protip'}


#### ✨ Note{-}

***All times are in Eastern Time (Canada)***
```

```{block, type='keynote'}

#### Keynote

```

```{block, type='speaker'}

#### Invited Speaker

```

```{block, type='session'}

#### Regular Session

```

```{block, type='social'}

#### Social Session

```

```{block, type='vendor'}


#### Vendor

```

```{block, type='workshop'}


#### Workshop

```

---

## Bureau d’accueil ouvert | 10:00 - 12:30 {-}

## Bienvenue à la conférence, annonces et reconnaissance des terres | 10:30-11:00 {-}


## Discours d’ouverture | 11:00-12:00    {-}


```{block, type='keynote'}
 

#### The (un)bearable lightness of student data privacy: reckonings and re-imaginings {-}

*Paul Prinsloo*
*University of South Africa*

<details>
<summary>**Abstract**</summary>
<p>


L’éducation a toujours collecté et utilisé des données sur l’apprentissage des élèves en combinaison avec une gamme d’autres données, par exemple des données démographiques, financières et d’apprentissage antérieur à diverses fins, telles que l’évaluation et le suivi des progrès des élèves, l’identification des élèves qui pourraient avoir besoin d’un soutien supplémentaire. Il y a toujours eu des inquiétudes concernant les préjugés possibles, les stéréotypes et l’impact de la catégorisation des élèves. La confidentialité (des données) (apprentissage) des étudiants se trouvait quelque part parmi les fichiers transportés d’un bureau à l’autre, les fichiers égarés, les stockages déverrouillés et, éventuellement, une approche de laisser-faire pour protéger la confidentialité des données des étudiants, car ce qui s’est passé dans la salle de classe et l’école, sont restés dans la salle de classe (surtout). Même si cette représentation de la confidentialité des données des étudiants peut sembler idéaliste et plutôt simpliste, nous devons tenir compte de la façon dont la numérisation et la datafication croissantes de l’enseignement et de l’apprentissage modifient non seulement la portée de la confidentialité (des données) des étudiants, mais tentent également de protéger leur (et notre) données. Dans cette présentation, j’espère provoquer une réflexion sur la légèreté (in)supportable de la confidentialité des données des étudiants et examiner ce que cela signifie pour les étudiants, les professeurs et la gouvernance des données institutionnelles au milieu de l’intensification et de l’expansion du regard sur les données.
</p>
</details>


```

## Casser | 12:00-12:30 {-}

## Non-conférence sur l’éducation numérique, en ligne et ouverte (en ligne via Zoom) | 12:30-1:15 {-}

(45 minutes)


Une non-conférence est une session axée sur les participants destinée à réduire l’accent mis sur les discours formels et à éviter les aspects hiérarchiques d’une session de conférence didactique. Tous les participants au Congrès sont invités à participer à cette contre-conférence en ligne ; cependant, les participants inscrits à la conférence OTESSA recevront une invitation à suggérer des sujets et à voter pour sélectionner à l’avance les sujets de la salle de sous-commission. Au moment de cette session, les affectations du sujet à la salle de sous-commission seront terminées et publiées sur le site Web de notre programme à l’adresse <https://otessa.org/2023/program/>. Vous êtes invités à vous déplacer entre les salles de discussion thématiques et à aller et venir à votre guise ! Nous nous réjouissons d’accueillir des discussions ciblées sur vos sujets favoris ! Il y aura également une contre-conférence en personne qui aura lieu le mardi 30 mai de 11h00 à 12h00 dans le bâtiment des sciences de la vie de l’Université York dans le cadre de la conférence OTESSA.

###  [Topic Survey](https://surveys.otessa.org/index.php/761431?lang=en) {-}

### [Voting Survey](https://surveys.otessa.org/index.php/858459?lang=fr){-}


### Topic List & Google Docs {-}



- [Co-design of courses, curriculum, and OERs / Inventory useful of free and open source projects for teaching and learning, organized by desktop, hosted, server.](https://docs.google.com/document/d/1Wn8PBfTJsHJ5hGipNzEyMoViq4fvTirjj6VQm36ghbQ/edit?usp=sharing){target="_blank"}
- [How to energize the present/inspire the future of EdTech in Education/Society](https://docs.google.com/document/d/1CYpwgI5_f6DIM9Izu6tagCbKPnTocFECqA0OUJDnT9g/edit?usp=sharing){target="_blank"}
- [Fostering digital literacy with leadership/design-makers](https://docs.google.com/document/d/1wl501fSK2J1XL0WniF8cYEXlG6n8r14donxVMjX_7F4/edit?usp=sharing){target="_blank"}  


## Casser | 1:15-1:30 {-}

## Séance simultanée 18 | 1:30-3:00 {-}

1.5 heures

### Séance simultanée 18.1 |  Formations d’apprentissage et d’enseignement en ligne {-}


```{block, type='workshop'}


#### 1:30-2:30 | **L’évaluation à l’ère numérique : l’apprentissage dans le continuum de la pédagogie, de la technologie et de l’évaluation** |  Workshop {-}

***Barbara Brown & Nadia Delanoy*** | *University of Calgary*

***Jodie Walz*** | *Calgary Catholic School District*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
À la suite d’une observation selon laquelle les futurs enseignants et les enseignants en poste ont besoin de plus d’opportunités pratiques pour s’engager dans des pratiques d’évaluation numériques afin de se préparer à des environnements d’apprentissage plus technologiques, une collaboration de recherche et de pratique a émergé entre une faculté d’éducation et un district scolaire. technologues en éducation. Cette étude basée sur la conception impliquait la conception d’une série d’apprentissage professionnel en ligne visant à développer les pratiques d’évaluation formative et sommative des enseignants à l’aide de pratiques améliorées par la technologie. En engageant les participants dans la réflexion et le temps de s’engager avec des méthodes améliorées par la technologie, nous avons utilisé une théorie pour mettre en pratique la conception ainsi que le cadre TPACK pour explorer la relation entre : (1) la technologie, (2) la pédagogie de l’enseignement et (3) le contenu connaissance. Les résultats de cette étude ont démontré l’importance de concevoir l’évaluation à travers une lentille interconnectée donnant la priorité à la centralité des connaissances technologiques, pédagogiques et de contenu. De plus, la recherche a indiqué l’efficacité des participants lorsqu’ils s’engagent dans des applications pédagogiques d’évaluation avec des constructions technologiques adaptées à leurs environnements d’enseignement et d’apprentissage. Les complexités en cours pendant la durée de ce travail ont couvert non seulement le début de la pandémie, mais maintenant les réalités intégrées dans un contexte post-pandémique émergent.

</p>
</details>
```


```{block, type='session'}

#### 2:30-3:00 | **Réflexions sur une stratégie nationale émergente pour l’éducation ouverte** |  Report {-}

***Bradley Wuetherick*** | *University of British Columbia – Okanagan Campus*

***Valerie Irvine*** | *University of Victoria*

***Ann Ludbrook*** | *Toronto Metropolitan University*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Au cours de la dernière décennie, les établissements d’enseignement supérieur, les organisations et les gouvernements ont plaidé en faveur de l’éducation ouverte et y ont investi, en se concentrant particulièrement sur la manière dont l’éducation ouverte peut atténuer les problèmes d’accessibilité et d’abordabilité. Et bien qu’il y ait eu un certain nombre d’initiatives pour coordonner ces activités, il n’y a pas eu de stratégie nationale pour l’éducation ouverte au Canada. Au cours des deux dernières années, les défenseurs de l’éducation ouverte (professeurs, bibliothécaires, administrateurs et représentants d’organisations à travers le pays) ont commencé à se réunir pour travailler à l’élaboration d’une stratégie nationale d’éducation ouverte. Pour faire avancer ce travail, ils ont travaillé ensemble pour organiser un sommet national suivi de deux sommets supplémentaires, axés sur les REL francophones et l’intersection des connaissances autochtones et des REL. Cette session se concentrera sur les réflexions de quatre personnes impliquées dans ces conversations nationales, en se concentrant sur l’élan derrière le développement d’une stratégie nationale d’éducation ouverte, l’importance des trois sommets (déjà organisés ou prévus), et pourquoi le développement d’un stratégie est une priorité pour l’enseignement supérieur canadien.TBA
</p>
</details>
```


### Séance simultanée 18.2 |  Formations d’apprentissage et d’enseignement en ligne {-}


```{block, type='session'}

#### 1:30-2:00 | **Recherche en éducation ouverte : passé, présent, futur** |  Recherche {-}

***Robert Farrow, Beck Pitt, Martin Weller, Paco Iniesto & Carina Bossu*** | *The Open University*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Le Global OER Graduate Network (GO-GN, s.d.) soutient la recherche doctorale en éducation ouverte dans le monde entier et compte actuellement plusieurs centaines de membres qui sont des chercheurs doctorants/post-doctoraux et des praticiens experts intéressés. Dans cette présentation, nous proposons une analyse des tendances de la recherche sur l’éducation ouverte, en nous appuyant sur les données générées par GO-GN ainsi que sur d’autres recherches d’experts.

Nous fournissons une analyse de l’activité du réseau et identifions les principaux domaines de la recherche contemporaine sur l’éducation ouverte, y compris la pratique ouverte, les REL en tant que domaine disciplinaire, l’établissement de liens entre les clusters de recherche et l’application des REL dans des contextes d’apprentissage non traditionnels. Nous proposons également quelques réflexions sur la nature évolutive du discours autour de l’éducation ouverte et la relation entre la recherche et la pratique, en particulier autour des thèmes de la justice sociale et de l’équité, de la diversité et de l’inclusion.

</p>
</details>
```

```{block, type='session'}


#### 2:00-2:30 | **Utilisation d’une enquête qualitative en ligne comme méthode de recherche au milieu de la pandémie de COVID** |  Pratique {-}

***Yina Liu*** | *University of Alberta*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
L’enquête en ligne devient l’une des méthodes populaires / préférées pour mener des recherches dans le cadre de la pandémie de Covid-19. La méthode permet aux chercheurs de collecter des données sans interaction en personne, fournit également des processus pratiques pour les chercheurs et les participants pour engager une enquête en termes de livraison d’enquêtes et de réponses. Cependant, les situations réelles de collecte de données peuvent ne pas être décrites comme pratiques. Cet article présentera une étude autoethnographique des propres expériences d’un chercheur en matière de réalisation d’enquêtes qualitatives en ligne pendant le Covid-19 au Canada. Le chercheur a utilisé un sondage qualitatif en ligne pour explorer les pratiques de littératie numérique des enfants nouveaux arrivants et les points de vue de leurs parents sur les pratiques numériques. Cette présentation fournira des suggestions aux futurs chercheurs en matière d’enquêtes, en termes de stratégies efficaces de collecte de données.

</p>
</details>
```

```{block, type='session'}


#### 2:30-3:00 | **La distance technologique : une nouvelle façon de conceptualiser la 
« distance » dans l’enseignement à distance** |  Recherche {-}

***Jon Dron*** | *Athabasca University*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Cet article présente le concept de distance technologique, qui décrit un écart entre les technologies (au sens large pour inclure les méthodes, les outils, les principes et les processus) disponibles pour qu’un apprenant puisse apprendre, et celles nécessaires pour compléter cet apprentissage. Cet écart est une mesure à la fois de la participation et de l’autonomie des apprenants dans le processus. Les technologies disponibles peuvent inclure celles fournies par les enseignants et les institutions ainsi que par de nombreux autres, notamment les apprenants eux-mêmes. Cependant, les technologies qui composent l’assemblage ne sont que des composants. Ce qui compte le plus, c’est la façon dont les apprenants comblent les lacunes entre eux pour atteindre leurs objectifs d’apprentissage. Celles-ci sont fondamentalement situées, idiosyncratiques et humaines. La distance technologique fournit de nouvelles perspectives sur d’autres modèles qui utilisent des métaphores spatiales, telles que la présence de communautés d’enquête et la distance transactionnelle.

</p>
</details>
```

### Séance simultanée 18.3 |  Caractère générique {-}


```{block, type='session'}


#### 1:30-2:00 | **Coaching en ligne non directif basé sur les forces dans l’enseignement supérieur** |  Recherche {-}

***Carolyn Kristjansson*** | *Trinity Western University*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Les modes d’enseignement supérieur en ligne et mixtes sont devenus de plus en plus répandus ces dernières années, se traduisant souvent par des espaces d’apprentissage en ligne composés d’apprenants adultes ayant un large éventail d’expériences de vie issues de contextes culturels et linguistiques variés. Une considération clé est de savoir comment soutenir au mieux ces apprenants pour faciliter un sentiment d’appartenance et d’engagement (Jeng, Bosch et Perry, 2023), conditions que certains chercheurs considèrent comme fondamentales pour la réussite scolaire (Roddy, et al., 2017). Une possibilité est le coaching. Cette présentation rend compte des premiers résultats d’une étude de cas portant sur l’expérience d’étudiants en matière de soutien non directif au coaching en ligne basé sur les forces dans le cadre d’un programme de maîtrise en enseignement de l’anglais aux locuteurs d’autres langues (MA TESOL).

L’étude de cas est guidée par des compréhensions théoriques de l’environnement d’apprentissage en tant que système dynamique complexe (Dornyei, 2014) et du coaching en tant que pratique sociale (Auteur) qui peut être caractérisée par des états d’attracteurs émotionnels positifs ou négatifs (Boyatzis, Rochford, & Taylor, 2015). La présentation donne un aperçu de l’analyse quantitative et qualitative préliminaire pour éclairer la valeur de l’expérience de coaching en ligne du point de vue des étudiants diplômés qui ont été coachés.

</p>
</details>
```

```{block, type='session'}


#### 2:00-2:30 | **L’auto-efficacité et la conviction de l’enseignant dans la mise en œuvre de S STEM, iSTEM ou STEAM dans sa classe** |  Recherche {-}

***Atiya Razi*** | *University of Windsor*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Ces dernières années, STEM, iSTEM (STEM intégré) et STEAM (paradigmes STEM) ont révolutionné le paradigme éducatif. Les chercheurs, les éducateurs et les professionnels du monde entier considèrent les paradigmes STEM comme leurs sauveurs (Kuenzi, 2008), qui ont pris en compte et réinventé l’archétype éducatif. Cette étude est fondée sur la théorie de l’auto-efficacité de Bandura et les théories d’apprentissage socioculturelles constructivistes. La réussite de la prestation des STEM, iSTEM et STEAM est liée à l’auto-efficacité et aux croyances des enseignants dans leur classe, car elle motive les élèves, développe une attitude positive envers les matières STEM et améliore les compétences des élèves au 21e siècle (Kanadlı, S., 2019 ). Cette étude vise à combler une lacune dans la recherche en examinant les perspectives des enseignants sur les paradigmes STEM et leur intégration en explorant les pédagogies actuelles et passées. Les chercheurs et les éducateurs bénéficieront également de cette étude en explorant les défis des enseignants lors de la mise en œuvre des paradigmes STEM dans leurs salles de classe. Enfin, l’étude examine les facteurs qui soutiennent les enseignants dans la mise en œuvre des paradigmes STEM en classe. Une approche à méthodes mixtes sera employée, impliquant des enquêtes et des entretiens. Les résultats de cette étude offriront une base de connaissances solide aux étudiants, éducateurs, chercheurs et décideurs intéressés avec les stratégies nécessaires à la réussite de l’exécution des STEM à l’école ; développement professionnel; générer et concevoir la politique d’éducation qui soutient l’éducation STEM, le développement de carrière STEM et le marché du travail, en particulier au Canada.

</p>
</details>
```

```{block, type='vendor'}

#### 2:30-3:00 | **Leveraging Social Annotation in the Age of AI** |  Research {-}


***Jessica Fuller*** | *hypothes.is*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
The emergence of cutting-edge technologies, like ChatGPT, has sparked a critical conversation throughout the world of education. In this session, Jessica from Hypothesis will show how to leverage social annotation to encourage authentic, process-oriented engagement with course materials. She’ll also share best practices for using social annotation with AI writing tools and demonstrate how to set up Hypothesis-enabled readings in your LMS. Participants can expect to leave the session armed with concrete assignment ideas to implement in courses right away.
</p>
</details>
```

### Séance simultanée 18.4 |  Aborder les inégalités {-}


```{block, type='session'}


#### 1:30-2:30 | **Quatre perspectives de la co-création apprenant-éducateur
** |  Recherche {-}

***Mercedes Lock*** | *Cambrian College*

***Jane Tyerman*** | *University of Ottawa*

***Lillian Chumbley*** | *Trent University*

***Laura Killam*** | *Queen’s University Canada*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Dans cette table ronde, nous discuterons des défis et des avantages de la co-création apprenant-éducateur à partir d’une variété de perspectives interdisciplinaires. Notre objectif sera de répondre aux questions du public sur la co-création apprenant-éducateur. Nous apporterons également quelques questions courantes que nous avons reçues des autres pour commencer la conversation si le public a besoin de temps pour réfléchir à ses questions.

Les panélistes représenteront différents aspects de la co-création à travers les utilisations académiques et de développement professionnel. Les panélistes ont de l’expérience dans la mise en œuvre et le soutien de la co-création en tant qu’apprenants, étudiants, éducateurs, partenaires et personnel de soutien dans les cours de premier cycle et des cycles supérieurs, le développement professionnel et les contextes de l’industrie.

La table ronde sera soutenue par un backchannel virtuel qui favorisera l’engagement des participants dans la discussion, permettra le crowdsourcing de notes et de matériel et posera des questions. Notre espoir est de créer une discussion significative pour soutenir ceux qui découvrent la co-création ou qui cherchent des moyens d’améliorer leur pratique de la co-création.

</p>
</details>
```

```{block, type='session'}

#### 2:30 - 3:00  | **Une boîte à outils de co-création apprenant-éducateur** |  Pratique {-}

***Laura Killam*** | *Queen’s University Canada*

***Lillian Chumbley*** | *Trent University *

***Jane Tyerman*** | *University of Ottawa*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
La co-création se produit lorsque les apprenants et les éducateurs travaillent ensemble pour prendre des décisions pendant un cours. La prise de décision partagée peut se produire en relation avec un ou plusieurs composants d’un cours, tels que la conservation du contenu ou la conception d’évaluations. Ce partenariat présente de nombreux avantages potentiels, notamment l’autonomisation des élèves, la promotion de meilleures relations et la métacognition, mais les éducateurs peuvent hésiter à l’essayer parce qu’ils sont préoccupés par les limites pragmatiques. Ces limitations peuvent inclure le temps nécessaire, les exigences techniques et l’engagement de grandes classes. En outre, des questions sur les problèmes d’intégrité académique peuvent survenir.

Dans cette présentation, nous partageons et recherchons une collaboration sur une ébauche de boîte à outils pour la co-création apprenant-éducateur. Notre objectif est de fournir un emplacement où les éducateurs peuvent facilement accéder à des outils qui les aideront à s’engager efficacement dans la co-création liée à un éventail de décisions d’apprentissage, petites à plus grandes. Dans cette présentation, nous discuterons des possibilités d’améliorer cette boîte à outils et de nous engager dans une communauté de pratique continue.

</p>
</details>
```

### Séance simultanée 18.5 |   Maintenir un changement positif {-}





```{block, type='session'}

#### 1:30 - 2:30  | **Mise à l'échelle petite : Lancement et plate-forme du collectif Open Book** |  Pratique {-}

***Judith Fathallah*** | *Lancaster University*


<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
L’Open Book Collective, dont le lancement est prévu en novembre 2022, rassemble des éditeurs de livres en libre accès, des bibliothécaires universitaires et des fournisseurs d’infrastructure OA, travaillant à un avenir durable et équitable pour les livres OA. Cette session présentera notre travail, puis démontrera l’utilisation de la plateforme d’adhésion Open Book Collective, qui sera en ligne au moment de la conférence. L’Open Book Collective fonctionne selon le principe de Scaling Small, qui a guidé les travaux de son projet parapluie, Community-Led Open Infrastructures for Open Access Books (COPIM). La « mise à l’échelle petite », par opposition à la « mise à l’échelle », est une autre façon d’envisager un écosystème de publication et de distribution pour les livres en libre accès qui est basé sur la confiance mutuelle et d’autres types de collaboration plutôt que sur la concurrence et l’incorporation. Nous pensons que les économies d’échelle aplanissent la diversité des communautés et conduisent à des monopoles malsains. Plus pragmatiquement, l’OBC exige un engagement de nos membres éditeurs à s’éloigner des frais de traitement des livres, qui sont à la fois insoutenables et profondément inéquitables. L’introduction et la démonstration interactive seront suivies d’une séance de questions-réponses.

</p>
</details>
```

```{block, type='session'}


#### 2:30-3:00 | **Recherche ? Quelle Recherche ? Technologie, évaluation et enseignement supérieur en tension** |  Recherche {-}

***Colin Madland*** | *University of Victoria*

<mark>**Reporté à partir de mardi**</mark>

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
En utilisant la théorie de l’apprentissage médiatisé par la technologie de Bower comme cadre, les participants seront invités à s’engager dans une conversation générative sur les approches possibles pour résoudre le problème des corpus de littérature fragmentés et cloisonnés liés à l’évaluation intégrée à la technologie dans l’enseignement supérieur. Les pratiques d’évaluation intégrées à la technologie dans l’enseignement supérieur font l’objet d’un examen minutieux avec une autre « menace existentielle » sous la forme de la génération automatisée de textes. Pour ceux dont les disciplines nécessitent une écriture ou un codage approfondi, cela a conduit à une certaine lamentation concernant ce qui semble être à risque : la capacité de croire que les apprenants se sont engagés dans le travail cognitif de création de sens et présentent les résultats de ce travail. Dans mes propres observations et dans le processus d’examen de la littérature sur l’évaluation intégrée de la technologie dans l’enseignement supérieur, les réponses à ce développement semblent correspondre à des corpus de littérature distincts avec de faibles liens entre eux. Les réponses semblent être orientées vers la technologie, les approches d’évaluation ou les perspectives disciplinaires individuelles. Les liens entre ces corpus de littérature cloisonnés et les difficultés sur le terrain à réagir aux défis de l’évaluation intégrée à la technologie dans l’enseignement supérieur seront problématisés et explorés et les participants engageront une conversation pour susciter et maintenir un changement positif pour le bien de l’académie. et la société.

</p>
</details>
```


## Casser | 3:00-3:15 {-}

## Social | 3:15-3:45 {-}


```{block, type='social'}

#### Music with Jon Dron, Athabasca University {-}

```

## Séance simultanée 19 | 3:45-5:15 {-}

1.5 heures

### Séance simultanée 19.1 |  Caractère générique {-}


```{block, type='session'}


#### 3:45-4:45 | **Sur la fiction éducative spéculative pour un avenir d’apprentissage plein d’espoir** |  Recherche {-}

***Shandell Houlden & George Veletsianos*** | *Royal Roads University*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Dans cette session, nous discutons de la réinvention des futurs de l’éducation en examinant les limites et les potentialités des méthodes de recherche spéculatives, en mettant l’accent sur la distinction dans la littérature entre les visions pessimistes du futur, qui sont des visions explorant des thèmes tels que la déconnexion, le manque d’autonomie et de souveraineté, et un contrôle technologique, corporatif, étatique et/ou autoritaire, et un avenir plein d’espoir. L’avenir de l’éducation spéculative pleine d’espoir est façonné par des thèmes tels que la connexion, l’agence et l’épanouissement communautaire et individuel, et suggère un virage vers les genres de l’hopepunk, du solarpunk et de la fiction visionnaire en tant que modèles de narration spéculative fondée sur l’espoir. Se concentrer sur ces futurs plus libérateurs sert à perturber la dépendance excessive à la narration pessimiste, qui est elle-même liée à la narration apocalyptique, qui risque de renforcer les inégalités, en particulier en ce qui concerne l’injustice coloniale des colons.

</p>
</details>
```

```{block, type='session'}

#### 4:45-5:15 | **Attends quoi? Examen des structures et des processus de financement du CRSH en mettant l’accent sur leurs répercussions sur l’accès équitable pour les chercheurs en éducation** |  Recherche {-}

***Valerie Irvine*** | *University of Victoria*

***Sonja Johnston*** | *University of Calgary*

<!--
**Keywords:**
-->

<details>
<summary>**Abstract**</summary>
<p>
L’accès au financement du gouvernement fédéral pour soutenir la recherche en sciences sociales a toujours été un processus hautement concurrentiel pour les professeurs et les étudiants diplômés. Alors que la recherche devient de plus en plus interdisciplinaire, nous observons des défis en termes d’assurer des voies pour soutenir un processus d’examen spécifiquement pour la recherche interdisciplinaire, tout en assurant un accès équitable au financement des trois organismes à travers les trois conseils (Conseil de recherche en sciences humaines (CRSH) , Conseil de recherches en sciences naturelles et en génie (CRSNG) et Instituts de recherche en santé du Canada (IRSC)) ainsi qu’entre disciplines au sein de comités au sein du CRSH. En tant que chercheurs en éducation, nous avons noté des tendances qui désavantagent peut-être les chercheurs en éducation, hébergés dans les facultés d’éducation. Nous aborderons également le fardeau supplémentaire qui marginalise les chercheurs et les étudiants diplômés en technologie éducative, qui font face à un « deuxième virage » en termes de développement et de mise à jour continus des littératies numériques et des pédagogies d’apprentissage en ligne. Au cours de cette séance, nous examinerons les données accessibles au public et partagerons des observations personnelles sur le processus, y compris une expérience directe en tant qu’examinateur répété des demandes de doctorat du CRSH à Ottawa. Nous partagerons les mesures prises pour ouvrir le dialogue et formuler des recommandations pour les prochaines étapes, car nous espérons collecter des données pour éclairer les recommandations de changement. Nous invitons les participants à fournir des commentaires sur les stratégies visant à créer un changement pour un accès équitable au financement de l’éducation.TBA

</p>
</details>
```

### Séance simultanée 19.2 |  Maintenir un changement positif {-}


```{block, type='session'}


#### 3:45-4:45 | **“« Plus silencieux ! » Les femmes universitaires racialisées s’expriment** |  Recherche {-}

***Sandra Dixon*** | *University of Lethbridge*

***Cecille DePass*** | *University of Calgary*

***Dawn Edge*** | *The University of Manchester*

***Mille Batta*** | *University of Lethbridge*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Étant donné que les femmes universitaires racialisées subissent un impact négatif dans le milieu universitaire (Association canadienne des professeures et professeurs d’université [ACPPU], 2018; National Center for Education Statistics [NCES], 2020), cette recherche contribue directement à promouvoir des changements positifs dans le milieu universitaire et la société en général. La question de recherche explore : Comment la bourse et la recherche sur l’équité, la diversité et l’inclusion (EDI) chez les femmes universitaires racialisées peuvent-elles améliorer et renforcer plusieurs disciplines, l’élaboration de politiques et l’administration dans le milieu universitaire ? Cette enquête s’aligne sur la mission d’OTESSA de faire progresser la recherche innovante et de diffuser les résultats des données dans le cadre de la mobilisation des connaissances. Cette session soutient le thème de la conférence puisqu’elle vise à promouvoir l’EDI dans l’éducation, l’érudition et la société. Fondée sur la recherche, cette présentation jette les bases d’une prise de conscience politique et institutionnelle accrue, d’un développement communautaire inclusif et d’une sensibilité culturelle au sein du milieu universitaire. La théorie de l’intersectionnalité qui sous-tend ce travail révèle une image complexe des façons dont les groupes racialisés sont altérés dans la société (Crenshaw, 1989). L’analyse de documents (Morgan, 2022), l’approche méthodologique qui sous-tend cette recherche explore un récit à la première personne des actions, des expériences, des croyances et des visions du monde d’un individu (Bowen, 2009). Cette session se termine par un appel à l’action qui propose des stratégies concrètes pour éclairer les politiques et les pratiques à l’échelle provinciale, nationale et internationale. Les participants seront invités à explorer des questions stimulantes et à réfléchir à la manière dont ils naviguent dans des contextes académiques racialisés.

</p>
</details>
```

```{block, type='session'}


#### 4:45-5:15 | **L’éducation à la paix dans la société à plateformes : les leçons de la Colombie** |  Recherche {-}

***Estaban Morales*** | *University of British Columbia*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
En Colombie, l’éducation à la paix a été reconnue comme essentielle pour changer les récits de violence dominants. Et, alors que l’éducation à la paix cherche à répondre aux vies et aux besoins des citoyens, il est devenu de plus en plus nécessaire d’examiner comment la paix et la violence sont transformées par les plateformes numériques telles que les médias sociaux. En effet, des plateformes telles que Facebook, Twitter et WhatsApp ont transformé la façon dont les Colombiens vivent et interagissent avec les écologies de la violence qui les affectent, eux et leurs communautés. En conséquence, cet article explorera comment la réflexion, le dialogue et l’imagination sur la violence dans les médias sociaux sont des lieux d’apprentissage transformateur. Dans cette étude, 18 jeunes adultes colombiens ont exploré, discuté et réfléchi sur la violence des médias sociaux telle qu’ils l’ont vécue dans leur vie quotidienne. Les résultats de cette étude montrent que les conversations critiques entre pairs peuvent soutenir les processus d’apprentissage des jeunes adultes en matière d’éducation aux médias et d’éducation à la paix, où ils peuvent mieux identifier, comprendre et traiter les comportements nuisibles en ligne et hors ligne. Dans l’ensemble, cette présentation souligne la nécessité d’intégrer les environnements numériques dans les efforts visant à construire et à maintenir des cultures de paix.

</p>
</details>
```

### Séance simultanée 19.3 |  Maintenir un changement positif {-}


```{block, type='workshop'}


#### 3:45-5:15 | **Concevoir une pédagogie pour des expériences immersives** |  Atelier {-}

***Joannie Girard*** | *Conseil scolaire Viamonde*

***S Girouard*** | *Conseil Scolaire Catholique Mon Avenir*

***Lorayne Robertson*** | *Ontario Tech University*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
La réalité virtuelle est une technologie où les utilisateurs sont immergés dans un monde numérique créé par un ordinateur et accessible via un casque (Dalton, 2021). Il a été démontré que la réalité virtuelle améliore l'apprentissage dans le cadre de la formation aux soins de santé et à la sécurité, car elle simule de manière vivante l'environnement réel. Les premières explorations de l'utilisation de la réalité virtuelle dans l'éducation montrent qu'elle offre une expérience de sortie sur le terrain rentable et visuellement stimulante qui engage les étudiants de nouvelles façons. Il y a cependant d'autres avantages à l'utilisation de la VR et ceux-ci sont liés au niveau d'immersion qu'elle procure à l'utilisateur. Dans un environnement VR immersif, les participants ont l'autonomie nécessaire pour explorer l'environnement virtuel, interagir avec des objets et d'autres personnes et créer des espaces adaptés aux différents besoins d'apprentissage. Dans l'atelier proposé, les participants pourront accéder à la réalité virtuelle via leur téléphone, leur ordinateur ou à l'aide d'un casque. L'atelier utilise Spatial, une plate-forme logicielle qui facilite la collaboration en temps réel dans l'environnement virtuel. Cette technologie a récemment été utilisée avec succès pour le perfectionnement professionnel des enseignants de l'Ontario dans les districts scolaires de langue française géographiquement éloignés. Dans cet atelier, les participants acquerront un sentiment de co-présence en réalité virtuelle et verront le potentiel d'utilisation de ces espaces d'apprentissage polysynchrones dans l'éducation.
</p>
</details>
```

### Séance simultanée 19.4 |  Maintenir un changement positif {-}


```{block, type='session'}


#### 3:45-4:15 | **Apprentissage basé sur la découverte avec des technologies ouvertes, pour un changement positif** |  Pratique {-}

***Brian Sutherland*** | *University of Toronto*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Les domaines de la conception et de l’informatique omniprésente ou omniprésente sous-tendent de nombreuses disciplines universitaires – peu ont été épargnées par la conception de systèmes, l’avènement des capacités de communication à haut débit et la prolifération des dispositifs informatiques. De plus en plus, ces relations sont facilitées par des cadres ouverts et des communautés en matière de matériel, de logiciel et de pédagogie. Dans cette session, je discute d’un cours de quatrième année en conception numérique où les étudiants en groupes se sont engagés avec des bibliothèques de codes ouverts et de petits ordinateurs pour créer des dispositifs et des systèmes de détection pour aider à un changement positif dans les soins de santé, la biologie et/ou l’environnement. Il renoue avec une pédagogie dite d’apprentissage par la découverte où l’issue est incertaine, les problèmes – complexes, et les savoirs – largement articulés et émergents. Les apprenants ont suivi des travaux pratiques guidés encadrés par d’autres étudiants, le personnel enseignant et des ressources en ligne, soutenus par leurs compétences en recherche et en évaluation, pour étayer leur développement rapide dans un domaine complexe, dans de nombreux cas jusqu’alors inconnu. Le résultat n’était pas tant des prototypes fonctionnels que des simulations de capacité et une riche compréhension conceptuelle des systèmes sociotechniques sous-jacents de développement, aidés par des compétences du XXIe siècle telles que la recherche et l’évaluation critique des sources, le réseautage en ligne, la collaboration de groupe, et la citoyenneté mondiale pour un changement positif.

</p>
</details>
```

```{block, type='session'}


#### 4:15-4:45 | **Co-création de simulations interprofessionnelles en soins de santé : une étude pilote** |  Recherche {-}

***Laura Killam*** | *Queen's University Canada*

***Jacqueline Vaughn, Alicia Sellon, Chase DuBois, Amelia Huelskamp, Andrea Smith, Colette Waddill & Justine Reel*** | *University of North Carolina Wilmington*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Contexte : La co-création, la formation interprofessionnelle et la simulation sont des stratégies qui peuvent préparer les étudiants en soins de santé à gérer les défis du monde réel en équipe. Le corps professoral a identifié à la fois un désir de s’engager dans une collaboration avec les étudiants et un besoin de tirer parti de la créativité des étudiants pour aider à combler l’écart dans les ressources disponibles sur le campus.

Objectif : Dans cette présentation, nous partageons les résultats d’une étude pilote multi-méthodes qui visait à tester le développement d’un cours dans lequel les étudiants se sont associés à des professeurs dans un défi de conception pour co-créer des simulations interprofessionnelles fondées sur des preuves. L’objectif de cette étude était d’évaluer la faisabilité du projet et les perceptions des étudiants sur la façon dont l’expérience a façonné leur apprentissage.

Méthodes : L’intervention consistait en un défi de conception de trois jours au cours duquel les étudiants ont co-créé une simulation avec le corps professoral dans des groupes interprofessionnels. Nous avons mesuré les compétences interprofessionnelles avant et après l’intervention, recueilli des commentaires ouverts sur l’apprentissage des étudiants et évalué la faisabilité (besoins en temps, ressources) de la co-conception d’une simulation par les étudiants.

Résultats : Cette stratégie s’est avérée faisable, efficace, unique et précieuse. Les étudiants ont exprimé le désir d’apprendre davantage dans le cadre de cette expérience. Conclusion : La co-création de simulation apprenant-éducateur peut être une stratégie viable pour améliorer les compétences interprofessionnelles des étudiants et enrichir l’apprentissage. D’autres recherches à plus grande échelle sont nécessaires.

</p>
</details>
```

```{block, type='session'}


#### 4:45-5:15 | **Négocier une théorie personnelle informée et une philosophie de l’éducation ouverte dans un cadre de développement professionnel** |  Recherche {-}

***Irwin DeVries*** | *Royal Roads University*

***Emily Schudel & Kimberlee Carter*** | *Kwantlen Polytechnic University*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Cette présentation est offerte par trois professionnels expérimentés de l’enseignement supérieur qui s’intéressent à l’enseignement ouvert. Il est axé sur leur propre pratique telle que reflétée dans un programme de développement professionnel qu’ils suivent, qui est le cadre de cette présentation. Ce programme se concentre non seulement sur les ressources et les techniques de l’éducation ouverte, mais aussi sur les buts et les objectifs de l’éducation ouverte, y compris les questions de justice sociale.

Au cours de cette session, les présentateurs partageront leurs réflexions sur leur expérience du premier cours du programme, axé sur la théorie et la philosophie de l’éducation ouverte. Ce cours a conduit les participants à explorer les histoires, les significations et les objectifs de l’éducation ouverte, tout en intégrant la littérature, les discussions et les exemples tirés de la propre pratique des participants.

Une approche collaborative réflexive critique (Hamilton & Pinnegar, 2014) est utilisée pour décrire, comparer et analyser leurs expériences. Nous abordons ces sujets dans la perspective que l’ouverture est « contextuelle, mais elle est aussi personnelle et continuellement négociée » (Cronin, 2017. P. 8) et donc nous situons notre compréhension dans nos pratiques individuelles.

</p>
</details>
```

## Casser | 5:15-5:30 {-}

## Séance Parallèle 20 | Conférenciers invités | 5:30-6:15 {-}

45 Minutes

### Séance Parallèle 20.1 {-}


```{block, type='speaker'}

#### Nadia Naffi | Université Laval {-} 

*Adopter le métaverse : FormationMeta et l'avenir de l'expérience d'apprentissage immersif (en français)*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Plongez dans le monde passionnant de FormationMeta, un projet exploratoire novateur de 14 semaines mené par la Chaire de leadership pédagogique sur les pratiques pédagogiques innovantes en contexte numérique de l’Université Laval, en partenariat avec la Bibliothèque de l’Université Laval et l’OVA. Ce projet novateur a offert aux concepteurs et aux enseignants d’expériences d’apprentissage de l’Université Laval une expérience authentique pour cultiver leurs compétences dans la conception et le développement d’expériences d’apprentissage immersives dans la réalité virtuelle et le métavers. Impliquant des étudiants de diverses disciplines telles que la technologie éducative, l’art et la conception de jeux, le projet a exploité la puissance du logiciel StellarX.ai pour créer une formation immersive sur mesure adaptée à la clientèle de la bibliothèque.

Présentée en français, cette conférence dévoilera des recommandations émergentes pour éclairer les équipes éducatives désireuses d’adopter des expériences d’apprentissage immersives. Le conférencier abordera des questions urgentes, notamment les possibilités actuelles et les avancées technologiques futures, telles que l’IA générative, les compétences essentielles pour développer des expériences d’apprentissage dans le métaverse et les stratégies de formation de groupes d’experts en éducation et en technologie éducative pour créer des expériences immersives qui répondent efficacement aux groupes d’apprenants tout en respectant des principes éthiques, équitables et inclusifs.

</p>
</details>
```

### Séance simultanée 20.2 {-}


```{block, type='speaker'}

#### Randy LaBonte | Vancouver Island University & Canadian eLearning Network{-} 

*Principes de conception pour l’apprentissage numérique et les normes NSQOL : points communs et différences*

<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
Rejoignez cette session pour acquérir une compréhension des principes de conception et d’organisation afin d’aider à informer la qualité des pratiques des enseignants et des leaders de l’apprentissage en ligne de la maternelle à la 12e année. Découvrez les principes de conception d’apprentissage en ligne basés au Canada et leurs points communs et leurs différences avec les normes nationales américaines pour un apprentissage en ligne de qualité (NSQOL), leur application à la pédagogie et à la pratique, et comment l’élucidation et la clarification des principes de conception et d’organisation aident à informer le leadership et politique administrative pour un apprentissage en ligne de qualité.

</p>
</details>
```

## Clôture de la conférence | 6:15-6:30 {-}

