# Unconference {-}

Our online Unconference (aka EdCamp) will be held on:

#### Friday, May 20 {-}

**12:45-1:45pm Eastern Time**


#### [VOTE NOW!](https://surveys.otessa.org/index.php/941512?lang=en){target="_blank"} {-}

##### [Session Link](https://app.forj.ai/en?t=/tradeshow/index&page=auditorium&id=1638304532451&auditorium_room_id=1647886846001){target="_blank"} {-}

Bring your thoughts for developing ideas and meeting other people with the same interests as you!

An Unconference (aka EdCamp) is a user-generated conference. There is no rigid pre-selection of session topics planned in advance. Instead, ideas for collaboration and conversation are determined as attendees identify common themes/topics that they would like to explore, and what they can teach others about.

Below is a great video from an in-person EdCamp Victoria that was designed for the K12 sector that explains the concept of an EdCamp well. In this instance, learners and instructors from the Faculty of Education at UVic had the opportunity to mix and share ideas with their field community of K12 teachers and administration. 

<iframe width="560" height="315" src="https://www.youtube.com/embed/VKi1Fiog9TE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Unconference approaches like this can be applied in any field of study to connect across their discipline (or mixing disciplines) and to mix stakeholder roles in the field (e.g., admin, educators, learners, etc.). This approach is also used in individual classes within a course. [See #EdCampUVic on Twitter](https://twitter.com/search?q=%23edcampuvic){target="_blank"} as a sample and a [sample archived EdCamp at UVic](https://edtechuvic.ca/edcamp/){target="_blank"}.

### Background on EdCamps {-}

>“What began as an idea has transformed into a movement. Since the original Edcamp in 2010 there have been over 700 conferences around the world in 25 countries. In the first few months following that first session in Philadelphia, the Edcamp movement grew and flourished in a grassroots manner. Each Edcamp is independently organized and hosted, is free to participants, bringing together passionate educators for a day of learning and growth. The conferences are participant-driven with the sessions developed and facilitated by the teachers who are attending and leverage social media to involve remote attendees.

>By adopting the unconference protocol inspired by the Barcamp model, Edcamps provide access to high quality, personalized professional learning for all educators. Embracing the belief that fellow educators can be some of the most valuable professional development resources for their colleagues, the Edcamp movement has been recognized by countless organizations, including the United States Department of Education, the Bammy Awards for Education, the Association for Supervision and Curriculum Development (ASCD), the International Society for Technology in Education (ISTE), the TEDx program and the Bill & Melinda Gates Foundation.”  www.edcamp.org

### How To Participate {-}

1. [Sign-Up & Contribute topics](https://surveys.otessa.org/index.php/761431?lang=en){target="_blank"}  
2. [Vote for your favourite topics](https://surveys.otessa.org/index.php/941512?lang=en){target="_blank"}. 

Or just show up, but the planning helps to make this a good event!

### Get Started {-}

1. [Complete **Sign-Up** and Contribute 3 Topics (DUE Wednesday Midnight)](https://surveys.otessa.org/index.php/761431?lang=en){target="_blank"}  
2. [**Vote NOW!!**](https://surveys.otessa.org/index.php/941512?lang=en){target="_blank"}  (DUE Fri 10am EDT)  
3. **Visit** the topics page to view the topics selected for the unconference and corresponding Google Docs for notes for each. These will be updated on the day of the Unconference, shortly after topic voting closes.
4. **Participate**! Access the Zoom Meeting link via the Congress platform. Share your ideas, resources, ask questions, brainstorm solutions for challenges, network, etc.

### Rules {-}

Follow Congress/OTESSA Code of Conduct, but we will highlight some rules below:

- Practice respect at all times.  
- No moderator required. Connect and share over a common interest.  
- You are most welcome to switch topics/rooms at any point. You are not committed to the full session.  
- Feel free to make use of the Google Docs to take notes (chat messages in Zoom will not be saved nor shared)  
- Topic voting and the video room link can be found on the Participate page  
- Consent needed to take screenshots of people to be posted on social media. We have created a space to take Zoom selfies in the “Social Media Photo Booth” breakout room.


### Topic List & Google Docs {-}

- [Human and Caring in the Open + Inclusive Practices for Online Teaching/UDL as Equity](https://docs.google.com/document/d/1Wn8PBfTJsHJ5hGipNzEyMoViq4fvTirjj6VQm36ghbQ/edit?usp=sharing){target="_blank"}  
- [Research Communities: Building Networks for Future Research Projects](https://docs.google.com/document/d/1Hn_9kd6mm1aQNYOeN4kWvBuAdjz_o_9KBJaKvdUvF6Y/edit?usp=sharing){target="_blank"}   
- [Grading Practices and Ungrading as a Mindset] and link to Google Doc to be Posted Friday AM  
- [Publishing in the OTESSA Journal] and link to Google Doc to be Posted Friday AM  
 

The number of topics will be based on the number of participants expected. The sign-up form will help us estimate how many topics/rooms, but we can also make changes in an emergent way at the time of the event.

### Google Docs for Overflow Rooms (impromptu convos) {-}

- Overflow Room #1: link to Google Doc to be Posted Friday AM  
- Overflow Room #2: link to Google Doc to be Posted Friday AM  


