# Presenter Information {-}


Come event day presenters and moderators will be let into the green room of the session **15 minutes in advance** of the start time. We will have a designated event technician who will be the host of the session and we can ensure the appropriate folks are made cohosts for screen sharing or other purposes.  

The session will have a waiting room activated and attendees won’t be admitted until the session start time.

Forj support is available, and they are extremely helpful. It is important to note that no links will be sent to presenters, and that it is helpful and important that presenters look at the platform before the start of their session. Presenters will get access shortly.

## Session Moderation {-}
Each session will be moderated by the presenter who is scheduled to present last during the session. The following guidelines have been provided by Congress.

Please contact support@otessa.org if you need urgent assistance.

## Land Acknowledgement {-}
Suggested virtual land acknowledgment statement:  
  
> I’d like to acknowledge the Indigenous Peoples of all the lands that we are on today. While we meet here on a virtual platform, we should take a moment to recognize the importance of the land on which we are each located. We acknowledge the territory to reaffirm our commitment and responsibility in building positive relationships between nations and in developing a deep understanding of Indigenous peoples and their cultures. From coast to coast to coast, we acknowledge the ancestral and unceded territory of all Inuit, First Nations, and Métis peoples.  

## Code of Conduct {-}

> In line with the Federation’s commitment to respectful, inclusive and collegial discourse and engagement, we ask that all attendees treat others with respect and abide by the Federation’s Code of Conduct during our time together online and on social media before, during and after the conference itself. The Congress Ombuds is available as an independent, neutral, and confidential resource for all Congress attendees to share their concerns and receive support in finding appropriate resolutions. For more information on the Federation’s Code of Conduct, please refer to the [Congress website under Registration](https://www.federationhss.ca/en/about-us/about-federation/code-conduct){target="_blank"}. The Congress Ombuds Team can be reached at congressh.ombuds@gmail.com. The Congress team will put both the URL link and the email address in the chat now, otherwise you can locate both at the Registration/Information greeting table found via the lobby.  

## Technical Notes {-}

### Audio/Video during presentations {-}

>We ask that you turn off your video and mute your audio for the duration of the presentation. We will invite you to turn on your video at the beginning of the Q&A period.  

### If this session is being recorded (keynotes and invited speakers only). {-}

>A reminder that this session will be recorded and made available on the platform within the next 72 hours. The platform will be available to all registered attendees until June 3rd. Parallel sessions will not be recorded.  

### Example text for Q&A {-}

> We will have 15 minutes at the end of the session and invite you to enter your question in the chat window. In support of having as many questions as possible answered, we ask you to stay on topic and be concise. If you wish to present your question verbally, please put your name in the chat window and we will call on you to ask your question by unmuting yourself and turning on your video (if you wish). We will try to address all questions, but may not be able to get to everyone’s question before the end of the session. (Enter your plan for post session answers to questions) If you wish to use the raise hand feature, this will require monitoring both the chat and participant list simultaneously.  

## Networking lounges {-}

>We encourage the conversation to continue even after this session has ended. Please head over to the networking lounge (the link can be found in your session links listing) to continue the conversation about this session.  

## Optional Technical Notes {-}

**Zoom Meeting view**: 

>We recommend that you change your view to speaker view which you can find in the top right-hand corner. If and when a presenter has shared their screen, at the top of your screen beside the green share screen bar that pops up, you will see viewing options available. Select side by side mode to view both the presenter and their presentation at the same time.  

## Optional Acknowledgements {-}

**Open/Funded** events only: 

> Thank you to the Federation for the Humanities and Social Sciences for partially funding this event through the International Keynote Speaker’s Fund or Aid for Interdisciplinary Fund.  

Other events:

> We would like to thank the Federation for the Humanities and Social Sciences and Forj for their support/help in making this virtual Congress possible.  

## Optional Q&A Notes {-}

>We understand and appreciate that during this session it is an opportunity to network with your peers. To help us monitor and not miss a question, we ask you to add the word QUESTION in capital letters before your question (or your name) to help guide us through all the dialogue in the chat.

## Green Room Discussions {-}

Chair/Host Housekeeping notes to be discussed in the 15-minute green room time period before the event:  

- To alert presenters that they are nearing the end of their presentation time, you will be **turning on your video at the 3-minute mark.**  
- During Q & A, it might be helpful to prepare a couple of questions to kick-start the Q & A.  
- When you are not speaking, turn off your video and ensure that your microphone is muted.  
- If the presenter is going overtime, the chair (you) may (at your discretion) **audibly intervene** to inform the presenter that they must conclude. Staying on time is imperative to a successful virtual session!  
- Prepare some speaking notes in the event that you need to jump in and chat with the audience unexpectedly due to technical and/or loss of presenter.  
- Promote the next session that will follow. [Check the OTESSA Program page for details.](https://otessa.org/2022/program){target="_blank"}  
- Be ready to monitor the timing of your session based on the amount of time of the session, the number of speakers and leave 15 minutes for Q&A and the last 3 minutes for a thank you and promotion of the next event. 

## Code of Conduct Concerns {-}

- The host/chair can also reach out to the Event Technician privately via chat about anything that they feel uncomfortable about or wish to take action on within the session. Congress Ombuds can be reached directly at congressh.ombuds@gmail.com.
- **Important**: The event tech will confirm with the chair/host that they (chair/host) will be the lead for decisions arising from a code of conduct concern. The event tech will be prepared to react, with direction from the chair/host, to do the following within the first 2 to 3 minutes:  
  - Mute the attendee presenting inappropriate discourse  
  - Turn off the video of the attendee  
  - Disengage chat and/or Q&A feature  
  - Remove attendee from the session and put them into the waiting room  
  - Submit via chat feature to the waiting room the following text:  
    > Under the guidelines of our Code of Conduct, we are committed to offering a safe space for all attendees. The conduct demonstrated did not support maintaining a safe space and therefore the decision was made to remove you from the session. You may reach out to the Congress Ombuds to discuss your concerns. Confidential email: Congressh.ombuds@gmail.com.  
- 
**Note:** the number of steps taken above will be determined by the chair/host.  

The chair/host does not need to expand on the situation that just occurred, but indicate that it is our intent to maintain a safe environment for all attendees. If any attendee feels they wish to discuss this matter after the session, the Congress Ombuds Team can be reached at the confidential email address of congressh.ombuds@gmail.com. The event tech will add the email address to the chat shortly.  

**Note:** If the event tech is not able to engage with the chair/host through chat after the 2-minute time period, the event tech will contact the Federation Duty Manager to assist and possibly make the decision. The Federation does not wish to intervene, and would prefer to have the association make the decision about their own attendees, however, the safety of all attendees is our top priority.

## Contingencies {-}

1. In the event that a presenter does not show up and the host has made a consistent effort to get in touch with them we will simply continue onto the next presenter. As all presenters should be online 15 minutes prior, if a presenter has not arrived in time for their actual presentation start time, we will not be able to wait for them...the show must go on!
2. Should folks be having serious internet issues we will recommend they either give their talk without a slide deck or stay off video or a combination of these things. If the chair is having connectivity issues, we will ask them to remain off video as well.
3. Should we need to exit a session and re-open a new one we will adjust the link in the virtual platform as quickly as possible.