--- 
title: "Programme de la conférence 2023"
author: "OTESSA Program Committee"
date: "Last updated `r format(Sys.time(), '%A, %b %d, %H:%M %p')`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: otessa/2023
description: "Open Technology in Education, Society, and Scholarship Association"
---

# Welcome and Acknowledgements {-}

```{block, type='protip'}
✨ Consultez le site Web de la conférence OTESSA à https://otessa.org/2023 pour les résumés et tout changement à ce programme. 


Des informations sur toute modification du programme seront également disponibles via le bureau d’accueil OTESSA sur la plate-forme de la conférence une fois la conférence ouverte.

```

Tous les participants OTESSA peuvent assister à la série de conférences « [Voir grand](https://www.federationhss.ca/en/congress/congress-2022/open-programming){target="_blank"} » du Congrès. Celles-ci ont lieu chaque jour de la conférence. Le Congrès propose également des “[événements ouverts](https://www.federationhss.ca/en/congress/congress-2022/calendar-open-events){target="_blank"}” (ouverts aux inscrits lors des conférences d’association au Congrès ainsi qu’à ceux qui détiennent des laissez-passer communautaires).

Tous les inscrits OTESSA peuvent également assister aux sessions de conférence offertes par [l’Association canadienne pour l’étude de l’éducation (CSSE)](https://csse-scee.ca/){target="_blank"}, [l’Association canadienne pour l’étude de l’enseignement supérieur (CSSHE)](https://csshe-scees.ca/){target="_blank"}, et [l’Association canadienne des revues savantes (CALJ)](https://www.calj-acrs.ca/){target="_blank"} car nous avons des accords de réciprocité en place. Veuillez noter que les présentateurs doivent s’inscrire à chaque conférence dans laquelle ils présentent.

```{block, type='protip'}


#### Rejoignez-nous à l’émission de radio matinale #OTESSA23 lundi, mardi, mercredi 29 30 31 mai de 6h30 à 7h30 (heure de l’Est) à [https://voiced.ca](https://voiced.ca){target="_blank"}

```
